[tool.poetry]
name = "globus-automate-client"
version = "0.11.5"
description = "Experimental client for the in-development Globus Automate services"
authors = [
    "Jim Pruyne <pruyne@globus.org>",
    "Rudyard Richter <rudyard@globus.org>",
    "Uriel Mandujano <uriel@globus.org>",
    "Jake Lewis <jake@globus.org>"
]
keywords = [
  "globus",
  "automation",
  "workflow",
  "action_provider",
  "command line"
  ]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "License :: Free To Use But Restricted",
  "Programming Language :: Python :: 3.6",
  "Programming Language :: Python :: 3.7",
  "Topic :: Internet :: WWW/HTTP",
  "Topic :: Software Development :: Libraries :: Application Frameworks",
  "Topic :: Software Development :: Libraries :: Python Modules"
  ]

readme = "README.rst"
license = "Apache-2.0"

[tool.poetry.scripts]
globus-automate = "globus_automate_client.cli.main:app"

[tool.poetry.dependencies]
python = "^3.6"
globus-sdk = "^2.0"
graphviz = "^0.12"
typer = {extras = ["all"], version = "^0.3.0"}
jsonschema = "^3.2.0"
PyYAML = "^5.3.1"
rich = "^9.12.2"

[tool.poetry.dev-dependencies]
pytest = "^5.0"
python-language-server = {version = "^0.36", extras = ["rope", "pyflakes", "pycodestyle"]}
pyls-black = "^0.4"
pyls-isort = "^0.2"
pyls-mypy = "^0.1"
jupyter = "^1.0.0"
sphinx = "^3.2.1"
rstcheck = "^3.3.1"
sphinx_material = "^0.0.30"
importmagic = "^0.1.7"
epc = "^0.0.5"
furo = "^2021.4.11-beta.34"
sphinx-copybutton = "^0.3.1"
typer-cli = "^0.0.11"
pypandoc = "^1.5"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true
line_length = 88
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
