
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-23T09:57:24-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "9b16ac31f69577ac81d2ddb760bd0d27e19d1ac8",
 "version": "1.4.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
