
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-25T12:12:45+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "76d7526e60a5ed0d45f9e074be81038e71eb13a7",
 "version": "0.7.0.post.dev220"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
