
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-23T09:55:36-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "3820af7d9e71872f8812402944c3051f7ef3ea7a",
 "version": "0.1.0a16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
