[tool.poetry]
name = "AlekSIS"
version = "2021.6rc1"
packages = [ { include = "aleksis_meta" } ]
include = ["LICNECE.rst"]
readme = "README.rst"

description = "Free School Information System Distribution"
authors = ["Dominik George <dominik.george@teckids.org>"]
maintainers = ["Jonathan Weth <wethjo@katharineum.de>", "Dominik George <dominik.george@teckids.org>"]
license = "EUPL-1.2-or-later"
homepage = "https://aleksis.org/"
repository = "https://edugit.org/AlekSIS/official/AlekSIS"
keywords = ["SIS", "education", "school", "digitisation", "school apps"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Framework :: Django :: 3.0",
    "Intended Audience :: Developers",
]

[tool.poetry.dependencies]
aleksis-core = "2.0rc2"
aleksis-app-alsijil = "2.0rc1"
aleksis-app-chronos = "2.0rc1"
aleksis-app-csvimport = { version = "2.0rc1", optional = true }
aleksis-app-dashboardfeeds = "2.0rc1"
aleksis-app-hjelp = "2.0rc1"
aleksis-app-ldap = { version = "2.0rc1", optional = true } 
aleksis-app-untis = { version = "2.0rc1", optional = true }

[tool.poetry.extras]
csvimport = ["aleksis-app-csvimport"]
ldap = ["aleksis-app-ldap"]
untis = ["aleksis-app-untis"]

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
