
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-18T13:05:16+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "edbb77da40d9f070ead3983e9bbcc2e7f2d8dc4d",
 "version": "2.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
