
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-19T12:00:28+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "6c670e016705e5464c09ccf54fad95a17ce3b2f9",
 "version": "0.3.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
