[tool.poetry]
name = "starsessions"
version = "1.0.0"
description = "Pluggable session support for Starlette."
authors = ["alex.oleshkevich <alex.oleshkevich@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6.2"
starlette = "^0.15.0"
itsdangerous = "^2.0.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
black = {version = "^21.6b0", allow-prereleases = true}
pytest-asyncio = "^0.15.1"
requests = "^2.25.1"
pytest-coverage = "^0.0"
flake8 = "^3.9.2"
mypy = "^0.910"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
norecursedirs = [".git", ".venv"]
addopts = "--tb=short -s"
testpaths = ["tests"]
