[package]
name = "robyn"
version = "0.2.1"
authors = ["Sanskar Jethi <sansyrox@gmail.com>"]
edition = "2018"
description = "A web server that is fast!"
license = "MIT"
homepage = "https://github.com/sansyrox/robyn"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "robyn"
crate-type = ["cdylib", "rlib"]

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]

[dependencies.pyo3-asyncio]
version = "0.13.3"
features =["tokio-runtime", "async-std-runtime"]

[dependencies]
tokio = { version = "1.7.0", features = ["full"] }
futures = { version = "0.3.6", default-features = false, features = ["async-await"] }
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"
route-recognizer = "0.2"
bytes = "0.5"
async-trait = "0.1"
hyper = { version = "0.14", features = ["full"] }
log = "0.4"
async-std = "1.9.0"
async-channel = "1.6.1"
crossbeam = "0.8.1"

[package.metadata.maturin]
name = "robyn"
