
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-22T10:16:23+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "93b51880eabff2623088f370cb55f09d8222cabe",
 "version": "3.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
