[tool.poetry]
name = "sparkypandy"
version = "0.1.0"
description = "It's not spark, it's not pandas, it's just awkward..."
authors = ["Tomas Pereira de Vasconcelos <tomasvasconcelos1@gmail.com>"]
license = "NA"

[tool.poetry.dependencies]
python = "^3.7"
pandas = "^1.2.4"
pyspark = "^3.1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
