
# This file was generated by a modified 'versioneer.py' from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

def get_versions():
    return {'version': '1.6.13', 'full-revisionid': 'b69bb2e2bbbff44416cf1565e7ddd1aae4483c29', 'dirty': False, 'error': None, 'date': '2021-06-24T19:15:40+0200'}
