from enum import Enum
from typing import Any, Optional

class Sensor(Enum):
    res_1080: Any = ...
    res_4k: Any = ...
    res_12_mp: Any = ...

class VideoMode(Enum):
    preview: int = ...
    video: int = ...

class Oak:
    def __init__(self, model_id: Optional[Any] = ..., sensor: Any = ..., video_mode: Any = ..., capture_depth: bool = ..., usb2: bool = ..., device_info: Optional[Any] = ...) -> None: ...
    @property
    def model_id(self): ...
    @property
    def model_purpose(self): ...
    @classmethod
    def get_devices_in_use(cls): ...
    @staticmethod
    def get_available_devices(): ...
    def get_frame(self): ...
    def get_model_result(self, block: bool = ..., **inference_args: Any): ...
    def get_model_data(self, block: bool = ...): ...
    def get_depth(self, block: bool = ...): ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self, type: Any, value: Any, traceback: Any) -> None: ...
