[project]
name = "doppler-pdm"
version = "1.0.0"
description = "A PDM plugin which allows commands to be run with environment variables from Doppler"
dependencies = [ "pdm~=1.6",]
requires-python = ">=3.9"
dynamic = [ "classifiers",]
[[project.authors]]
name = "Elijah Sink"
email = "theminorprofit@gmail.com"

[build-system]
requires = [ "pdm-pep517",]
build-backend = "pdm.pep517.api"

[project.license]
text = "MIT"

[project.urls]
homepage = "https://github.com/ElijahSink/doppler-pdm"

[project.optional-dependencies]

[project.entry-points.pdm]
run = "doppler_pdm.__init__:main"

[tool.pdm.dev-dependencies]
dev = [ "black~=21.6b0", "isort~=5.9", "pre-commit~=2.13",]

[tool.pdm.scripts._]
doppler = true

[tool.pdm.scripts.test]
cmd = "echo test"

[tool.pdm.scripts.test2]
cmd = "echo $CFRL_DOMAIN"
doppler = false
