
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-22T08:36:04+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "9a85ff8f575855de93cdd3263d5f81f5c63e5048",
 "version": "0.0.3.post0.dev1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
