
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-20T12:19:50-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "a07b28c330e5be386cf7067c41d28b2d5c9ef279",
 "version": "4.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
