[tool.poetry]
name = "light-scores"
version = "0.1.2"
description = ""
authors = ["freemt"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/ffreemt/light-scores"

[tool.poetry.dependencies]
python = "^3.7"
loguru = "^0.5.3"
rank-bm25 = "^0.2.1"
nltk = "^3.6.2"
logzero = "^1.7.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
tbump = "^6.3.2"
pydocstyle = "^6.0.0"
flake8 = "^3.9.1"
black = "^20.8b1"
ipython = "^7.22.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
