
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-21T16:01:14+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b5315beaa6ef2d02484d8fa5d78e2b707799410e",
 "version": "0.4.46"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
