# Generated by Django 3.1.7 on 2021-06-24 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.TextField()),
                ('name', models.TextField()),
                ('db_table', models.TextField()),
                ('is_admin', models.BooleanField(null=True, verbose_name='admin')),
                ('is_middleware', models.BooleanField(verbose_name='middleware')),
                ('count', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'django_objects_count_model',
                'ordering': ('app', 'name'),
            },
        ),
        migrations.AddIndex(
            model_name='model',
            index=models.Index(fields=['app'], name='django_obje_app_36b3ea_idx'),
        ),
        migrations.AddIndex(
            model_name='model',
            index=models.Index(fields=['name'], name='django_obje_name_466961_idx'),
        ),
        migrations.AddIndex(
            model_name='model',
            index=models.Index(fields=['db_table'], name='django_obje_db_tabl_e2f0b1_idx'),
        ),
        migrations.AddIndex(
            model_name='model',
            index=models.Index(fields=['is_middleware'], name='django_obje_is_midd_b3f1fe_idx'),
        ),
    ]
