
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-22T13:54:50-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "bdaabfe535b5ae24873f8141af09ce009997a484",
 "version": "0.1a2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
