[tool.poetry]
name = "neon-ml"
packages = [
    {include = "neon"}
]
version = "0.1.0"
description = ""
authors = ["yutayamazaki <tppymd@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
gensim = "^4.0.1"
numpy = "^1.21.0"

[tool.poetry.dev-dependencies]
mypy = "^0.800"
flake8 = "^3.8.4"
black = "^21.6b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
