[tool.poetry]
name = "puchipuchi_filler"
version = "0.1.0"
description = "nothing to describe"
authors = ["snara tkomatsu tkano"]

[tool.poetry.dependencies]
python = ">=3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

