
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-25T16:49:44+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "8bbfdf47fde192057df5b065c18aa60b256c882b",
 "version": "2.3.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
