
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-18T05:37:17-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "0b0484654af95d0c74c88d72a60ab5bc1455c228",
 "version": "0.16.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
