[tool.poetry]
name = "fuzzyduration"
version = "0.2.0"
description = "returns the number of seconds as the approx. largest unit of time."
authors = ["ccdale <chris.charles.allison+fuzzy@gmail.com>"]
readme = "README.md"
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
