
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-18T11:05:11+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "3e0fc5dc8f59406581d1ccaa5c0e5e737bb877b1",
 "version": "0.9.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
