from aioworkers.core.plugin import search_plugins as search_plugins
from typing import Any

logger: Any
ASGIApp: Any

class AsgiMiddleware:
    app: Any = ...
    context: Any = ...
    def __init__(self, app: ASGIApp, plugin: str=..., context: Any=...) -> None: ...
    async def __call__(self, scope: Any, receive: Any, send: Any) -> None: ...
    async def lifespan(self, receive: Any, send: Any): ...
    async def startup(self) -> None: ...
    async def shutdown(self) -> None: ...
