# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-13 15:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0019_auto_20181028_1638'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0008_historicalproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDuplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category_destination', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='categoryduplication_category_destination', to='categories.Category')),
                ('category_source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='categoryduplication_category_source', to='categories.Category')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDuplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_destination', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='projectduplication_project_destination', to='projects.Project')),
                ('project_source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='projectduplication_project_source', to='projects.Project')),
            ],
        ),
    ]
