
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-21T22:52:55-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "b2f8c2042c1f056eb4f28d7ab75c5718abcea835",
 "version": "2.1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
