from typing import Any

class OpenCV:
    net: Any = ...
    layer_names: Any = ...
    def __init__(self, model_config: Any) -> None: ...
    def forward(self): ...
    def set_input(self, input: Any) -> None: ...
    def set_backend(self, backend: Any) -> None: ...
    def set_accelerator(self, target: Any) -> None: ...
    def set_layer_names(self) -> None: ...
