from typing import Any

class TensorRT:
    net: Any = ...
    context: Any = ...
    stream: Any = ...
    def __init__(self, model_config: Any) -> None: ...
    def set_input(self, input: Any) -> None: ...
    def forward(self): ...

class CudaMemory:
    def __init__(self, host: Any, device: Any, shape: Any, dtype: Any) -> None: ...
    @property
    def host(self): ...
    @property
    def device(self): ...
    @property
    def shape(self): ...
    @property
    def dtype(self): ...
