from aioworkers.core.base import AbstractNamedEntity as AbstractNamedEntity
from aioworkers.net.web.exceptions import HttpException as HttpException
from collections import namedtuple
from typing import Any, Iterable, Mapping, Optional

Route = namedtuple('Route', 'handler kwargs')

class Application(AbstractNamedEntity):
    async def init(self) -> None: ...
    def add_route(self, method: Any, path: Any, handler: Any, name: Optional[Any] = ..., **kwargs: Any) -> None: ...
    async def handler(self, request: Any): ...

class Resources(Iterable):
    def __init__(self, resources: Mapping) -> None: ...
    def __iter__(self) -> Any: ...
