import asyncio
from ...http import URL as URL
from typing import Any

logger: Any

class Protocol(asyncio.Protocol):
    def __init__(self, server: Any) -> None: ...
    @classmethod
    def factory(cls, **kwargs: Any): ...
    def connection_made(self, transport: Any) -> None: ...
    def data_received(self, data: Any) -> None: ...
    def on_url(self, url: bytes) -> Any: ...
    def on_header(self, name: bytes, value: bytes) -> Any: ...
    def on_headers_complete(self) -> None: ...
    def on_body(self, body: bytes) -> Any: ...
    def connection_lost(self, exc: Any) -> None: ...
    def on_message_begin(self) -> None: ...
    def on_message_complete(self) -> None: ...
    def on_chunk_header(self) -> None: ...
    def on_chunk_complete(self) -> None: ...
