from ...core.formatter import registry as registry
from .exceptions import HttpException as HttpException
from typing import Any, Optional

class Request:
    url: Any = ...
    method: Any = ...
    headers: Any = ...
    transport: Any = ...
    context: Any = ...
    content_length: Any = ...
    def __init__(self, url: Any, method: Any, *, body_future: Optional[Any] = ..., headers: Any = ..., transport: Optional[Any] = ..., context: Optional[Any] = ...) -> None: ...
    def read(self): ...
    def response(self, data: Optional[Any] = ..., status: int = ..., reason: str = ..., format: Optional[Any] = ..., headers: Any = ...): ...
