
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-23T10:20:35-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "7918cd2bd656be68a33bab8ad2a6730d4059fb21",
 "version": "0.8.9b0.dev202106240707"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
