#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['mdformat_deflist']

package_data = \
{'': ['*']}

install_requires = \
['mdformat >=0.7.0,<0.8.0', 'mdit-py-plugins >=0.2.7,<0.3.0']

extras_require = \
{'dev': ['pre-commit'], 'test': ['pytest~=6.0', 'coverage', 'pytest-cov']}

entry_points = \
{'mdformat.parser_extension': ['deflist = mdformat_deflist']}

setup(name='mdformat_deflist',
      version='0.1.0',
      description='An mdformat plugin for markdown-it-deflist.',
      author='Chris Sewell',
      author_email='executablebooks@gmail.com',
      url='https://github.com/executablebooks/mdformat-deflist',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      entry_points=entry_points,
      python_requires='>=3.7',
     )
