name: CI

on:
  push:
    branches:
      - master
  pull_request:
#  schedule:
#    - cron: '0 0 * * 1'


jobs:
  pylint:
    name: codecheck-pylint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install -r requirements/test.txt
      - name: Run
        run: tox -e py38-codecheck-pylint
  flake8:
    name: codecheck-flake8
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install -r requirements/test.txt
      - name: Run
        run: tox -e py38-codecheck-flake8
  integration-tests:
    name: linux-integration-tests
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install
      run: sudo pip install . --force-reinstall
    - name: Execute r2env
      run: r2env list
    - name: Install r2 using r2env
      run: |
        r2env init
        r2env install radare2@latest
    - name: Execute latest r2 version
      run: |
        r2env use radare2@latest
        $HOME/.r2env/bin/r2 -v
    - name: Uninstalling
      run: sudo pip uninstall -y r2env && rm -rf $HOME/.r2env
