# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-06-08 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_actions', '0003_auto_20210608_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='field_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
