# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-06-09 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track_actions', '0005_auto_20210609_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ('-id',), 'verbose_name_plural': 'History model'},
        ),
    ]
