"""
    Algorithmia Management APIs

    APIs for managing actions on the Algorithmia platform  # noqa: E501

    The version of the OpenAPI document: 1.5.0
    Contact: support@algorithmia.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import algorithmia_api_client
from algorithmia_api_client.model.full_usage_row import FullUsageRow


class TestFullUsageRow(unittest.TestCase):
    """FullUsageRow unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFullUsageRow(self):
        """Test FullUsageRow"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FullUsageRow()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
