"""
    Algorithmia Management APIs

    APIs for managing actions on the Algorithmia platform  # noqa: E501

    The version of the OpenAPI document: 1.5.0
    Contact: support@algorithmia.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import algorithmia_api_client
from algorithmia_api_client.api.builds_api import BuildsApi  # noqa: E501


class TestBuildsApi(unittest.TestCase):
    """BuildsApi unit test stubs"""

    def setUp(self):
        self.api = BuildsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_commit_log_for_repository(self):
        """Test case for commit_log_for_repository

        List commits for a repository  # noqa: E501
        """
        pass

    def test_compile_algorithm(self):
        """Test case for compile_algorithm

        Compile algorithm  # noqa: E501
        """
        pass

    def test_compile_algorithm_by_id(self):
        """Test case for compile_algorithm_by_id

        Compile algorithm  # noqa: E501
        """
        pass

    def test_get_algorithm_build_by_id(self):
        """Test case for get_algorithm_build_by_id

        Get individual algorithm build by ID  # noqa: E501
        """
        pass

    def test_get_algorithm_build_logs(self):
        """Test case for get_algorithm_build_logs

        Get algorithm build logs  # noqa: E501
        """
        pass

    def test_get_algorithm_builds(self):
        """Test case for get_algorithm_builds

        Get algorithm builds  # noqa: E501
        """
        pass

    def test_get_algorithm_by_id_build_by_id(self):
        """Test case for get_algorithm_by_id_build_by_id

        Get individual algorithm build by ID  # noqa: E501
        """
        pass

    def test_get_algorithm_by_id_build_logs(self):
        """Test case for get_algorithm_by_id_build_logs

        Get algorithm build logs  # noqa: E501
        """
        pass

    def test_get_algorithm_by_id_builds(self):
        """Test case for get_algorithm_by_id_builds

        Get algorithm builds  # noqa: E501
        """
        pass

    def test_get_algorithm_scm_connection_status(self):
        """Test case for get_algorithm_scm_connection_status

        Get algorithm SCM connection status  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
