"""
    Algorithmia Management APIs

    APIs for managing actions on the Algorithmia platform  # noqa: E501

    The version of the OpenAPI document: 1.5.0
    Contact: support@algorithmia.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import algorithmia_api_client
from algorithmia_api_client.api.organizations_api import OrganizationsApi  # noqa: E501


class TestOrganizationsApi(unittest.TestCase):
    """OrganizationsApi unit test stubs"""

    def setUp(self):
        self.api = OrganizationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_organization_api_key(self):
        """Test case for add_organization_api_key

        Create an organization API key for a user  # noqa: E501
        """
        pass

    def test_add_organization_member(self):
        """Test case for add_organization_member

        Add a user as a member of a given organization  # noqa: E501
        """
        pass

    def test_create(self):
        """Test case for create

        Create an OrganizationType  # noqa: E501
        """
        pass

    def test_create_key_for_organization(self):
        """Test case for create_key_for_organization

        Create an AlgorithmKey for an organization  # noqa: E501
        """
        pass

    def test_create_organization(self):
        """Test case for create_organization

        Creates an organization owned by the caller  # noqa: E501
        """
        pass

    def test_create_organization_host_information(self):
        """Test case for create_organization_host_information

        Create new Organization Host Information  # noqa: E501
        """
        pass

    def test_delete(self):
        """Test case for delete

        Deletes the Organization Host Information for org named  # noqa: E501
        """
        pass

    def test_delete_by_name(self):
        """Test case for delete_by_name

        Remove an organization type by name  # noqa: E501
        """
        pass

    def test_delete_host_usernames(self):
        """Test case for delete_host_usernames

        Deletes functional-ids associated with a given algorithm  # noqa: E501
        """
        pass

    def test_delete_organization(self):
        """Test case for delete_organization

        Delete an organization  # noqa: E501
        """
        pass

    def test_edit(self):
        """Test case for edit

        Update an organization  # noqa: E501
        """
        pass

    def test_get_all_organization_types(self):
        """Test case for get_all_organization_types

        Get all organization types  # noqa: E501
        """
        pass

    def test_get_by_org_name(self):
        """Test case for get_by_org_name

        Get Organization Host Information  # noqa: E501
        """
        pass

    def test_get_host_usernames(self):
        """Test case for get_host_usernames

        List of all the AlgorithmHostUsername \"algorithm-id / functional-id\" pairs  # noqa: E501
        """
        pass

    def test_get_organization(self):
        """Test case for get_organization

        Get an organization represented by the provided orgName  # noqa: E501
        """
        pass

    def test_get_organizations(self):
        """Test case for get_organizations

        Lists all organizations  # noqa: E501
        """
        pass

    def test_get_utility_algorithms(self):
        """Test case for get_utility_algorithms

        List of utility algorithms  # noqa: E501
        """
        pass

    def test_list_keys(self):
        """Test case for list_keys

        List all the keys in an organization  # noqa: E501
        """
        pass

    def test_list_members(self):
        """Test case for list_members

        List of members with their roles in a given organization  # noqa: E501
        """
        pass

    def test_remove_organization_member(self):
        """Test case for remove_organization_member

        Remove a user from an organization  # noqa: E501
        """
        pass

    def test_set_host_usernames(self):
        """Test case for set_host_usernames

        Adds a list of algorithm-id / functional-id pairs  # noqa: E501
        """
        pass

    def test_update(self):
        """Test case for update

        Update existing Organization Host Information  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
