"""
    Algorithmia Management APIs

    APIs for managing actions on the Algorithmia platform  # noqa: E501

    The version of the OpenAPI document: 1.5.0
    Contact: support@algorithmia.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import algorithmia_api_client
from algorithmia_api_client.model.create_request_version_info import CreateRequestVersionInfo
from algorithmia_api_client.model.details import Details
from algorithmia_api_client.model.scms_user_pass_or_secret_token import SCMSUserPassOrSecretToken
from algorithmia_api_client.model.settings_mandatory import SettingsMandatory
from algorithmia_api_client.model.source_create import SourceCreate
globals()['CreateRequestVersionInfo'] = CreateRequestVersionInfo
globals()['Details'] = Details
globals()['SCMSUserPassOrSecretToken'] = SCMSUserPassOrSecretToken
globals()['SettingsMandatory'] = SettingsMandatory
globals()['SourceCreate'] = SourceCreate
from algorithmia_api_client.model.create_request import CreateRequest


class TestCreateRequest(unittest.TestCase):
    """CreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateRequest(self):
        """Test CreateRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
