"""
    Algorithmia Management APIs

    APIs for managing actions on the Algorithmia platform  # noqa: E501

    The version of the OpenAPI document: 1.5.0
    Contact: support@algorithmia.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import algorithmia_api_client
from algorithmia_api_client.api.connections_api import ConnectionsApi  # noqa: E501


class TestConnectionsApi(unittest.TestCase):
    """ConnectionsApi unit test stubs"""

    def setUp(self):
        self.api = ConnectionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_all_connections(self):
        """Test case for delete_all_connections

        deletes all the configured connections  # noqa: E501
        """
        pass

    def test_get_connection(self):
        """Test case for get_connection

        Gets the currently configured connection  # noqa: E501
        """
        pass

    def test_update_connection(self):
        """Test case for update_connection

        Sets the connection configuration  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
