"""
    Algorithmia Management APIs

    APIs for managing actions on the Algorithmia platform  # noqa: E501

    The version of the OpenAPI document: 1.5.0
    Contact: support@algorithmia.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import algorithmia_api_client
from algorithmia_api_client.model.algorithm_callability import AlgorithmCallability
from algorithmia_api_client.model.environment import Environment
from algorithmia_api_client.model.language import Language
from algorithmia_api_client.model.license import License
from algorithmia_api_client.model.network_access import NetworkAccess
from algorithmia_api_client.model.source_visibility import SourceVisibility
globals()['AlgorithmCallability'] = AlgorithmCallability
globals()['Environment'] = Environment
globals()['Language'] = Language
globals()['License'] = License
globals()['NetworkAccess'] = NetworkAccess
globals()['SourceVisibility'] = SourceVisibility
from algorithmia_api_client.model.settings import Settings


class TestSettings(unittest.TestCase):
    """Settings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSettings(self):
        """Test Settings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Settings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
