"""
    Algorithmia Management APIs

    APIs for managing actions on the Algorithmia platform  # noqa: E501

    The version of the OpenAPI document: 1.5.0
    Contact: support@algorithmia.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import algorithmia_api_client
from algorithmia_api_client.model.scm_user_o_auth_status_scm_organizations import ScmUserOAuthStatusScmOrganizations
globals()['ScmUserOAuthStatusScmOrganizations'] = ScmUserOAuthStatusScmOrganizations
from algorithmia_api_client.model.scm_user_o_auth_status import ScmUserOAuthStatus


class TestScmUserOAuthStatus(unittest.TestCase):
    """ScmUserOAuthStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScmUserOAuthStatus(self):
        """Test ScmUserOAuthStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ScmUserOAuthStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
