"""
    Algorithmia Management APIs

    APIs for managing actions on the Algorithmia platform  # noqa: E501

    The version of the OpenAPI document: 1.5.0
    Contact: support@algorithmia.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import algorithmia_api_client
from algorithmia_api_client.model.auth_permissions import AuthPermissions
globals()['AuthPermissions'] = AuthPermissions
from algorithmia_api_client.model.organization_api_key_creation import OrganizationApiKeyCreation


class TestOrganizationApiKeyCreation(unittest.TestCase):
    """OrganizationApiKeyCreation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrganizationApiKeyCreation(self):
        """Test OrganizationApiKeyCreation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OrganizationApiKeyCreation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
