"""
    Algorithmia Management APIs

    APIs for managing actions on the Algorithmia platform  # noqa: E501

    The version of the OpenAPI document: 1.5.0
    Contact: support@algorithmia.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import algorithmia_api_client
from algorithmia_api_client.model.directory_acl import DirectoryAcl
from algorithmia_api_client.model.file import File
from algorithmia_api_client.model.folder import Folder
globals()['DirectoryAcl'] = DirectoryAcl
globals()['File'] = File
globals()['Folder'] = Folder
from algorithmia_api_client.model.directory import Directory


class TestDirectory(unittest.TestCase):
    """Directory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDirectory(self):
        """Test Directory"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Directory()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
