"""
    Algorithmia Management APIs

    APIs for managing actions on the Algorithmia platform  # noqa: E501

    The version of the OpenAPI document: 1.5.0
    Contact: support@algorithmia.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import algorithmia_api_client
from algorithmia_api_client.model.kafka_plaintext_unauthenticated_connection_configuration import KafkaPlaintextUnauthenticatedConnectionConfiguration
from algorithmia_api_client.model.kafka_sasl_ssl_connection_configuration import KafkaSaslSslConnectionConfiguration
globals()['KafkaPlaintextUnauthenticatedConnectionConfiguration'] = KafkaPlaintextUnauthenticatedConnectionConfiguration
globals()['KafkaSaslSslConnectionConfiguration'] = KafkaSaslSslConnectionConfiguration
from algorithmia_api_client.model.connection_configuration_request import ConnectionConfigurationRequest


class TestConnectionConfigurationRequest(unittest.TestCase):
    """ConnectionConfigurationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConnectionConfigurationRequest(self):
        """Test ConnectionConfigurationRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConnectionConfigurationRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
