"""
    Algorithmia Management APIs

    APIs for managing actions on the Algorithmia platform  # noqa: E501

    The version of the OpenAPI document: 1.5.0
    Contact: support@algorithmia.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import algorithmia_api_client
from algorithmia_api_client.api.invites_api import InvitesApi  # noqa: E501


class TestInvitesApi(unittest.TestCase):
    """InvitesApi unit test stubs"""

    def setUp(self):
        self.api = InvitesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_invite(self):
        """Test case for add_invite

        Add an invite code  # noqa: E501
        """
        pass

    def test_delete_invite(self):
        """Test case for delete_invite

        Delete an invite code  # noqa: E501
        """
        pass

    def test_get_invites(self):
        """Test case for get_invites

        Get a list of invite codes  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
