"""
    Algorithmia Management APIs

    APIs for managing actions on the Algorithmia platform  # noqa: E501

    The version of the OpenAPI document: 1.5.0
    Contact: support@algorithmia.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import algorithmia_api_client
from algorithmia_api_client.api.auth_api import AuthApi  # noqa: E501


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self):
        self.api = AuthApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_key_for_user(self):
        """Test case for create_key_for_user

        Create an API key for a given user  # noqa: E501
        """
        pass

    def test_get_keys_for_user(self):
        """Test case for get_keys_for_user

        Get all API keys for a user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
