"""
    Algorithmia Management APIs

    APIs for managing actions on the Algorithmia platform  # noqa: E501

    The version of the OpenAPI document: 1.5.0
    Contact: support@algorithmia.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import algorithmia_api_client
from algorithmia_api_client.model.algorithm_host_username import AlgorithmHostUsername


class TestAlgorithmHostUsername(unittest.TestCase):
    """AlgorithmHostUsername unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAlgorithmHostUsername(self):
        """Test AlgorithmHostUsername"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AlgorithmHostUsername()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
