"""
    Algorithmia Management APIs

    APIs for managing actions on the Algorithmia platform  # noqa: E501

    The version of the OpenAPI document: 1.5.0
    Contact: support@algorithmia.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import algorithmia_api_client
from algorithmia_api_client.api.algorithms_api import AlgorithmsApi  # noqa: E501


class TestAlgorithmsApi(unittest.TestCase):
    """AlgorithmsApi unit test stubs"""

    def setUp(self):
        self.api = AlgorithmsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_call_algorithm(self):
        """Test case for call_algorithm

        Make a request to an algorithm  # noqa: E501
        """
        pass

    def test_call_algorithm_by_id(self):
        """Test case for call_algorithm_by_id

        Make a request to an algorithm by immutable identifier  # noqa: E501
        """
        pass

    def test_commit_log_for_repository(self):
        """Test case for commit_log_for_repository

        List commits for a repository  # noqa: E501
        """
        pass

    def test_compile_algorithm(self):
        """Test case for compile_algorithm

        Compile algorithm  # noqa: E501
        """
        pass

    def test_compile_algorithm_by_id(self):
        """Test case for compile_algorithm_by_id

        Compile algorithm  # noqa: E501
        """
        pass

    def test_create_algorithm(self):
        """Test case for create_algorithm

        Create algorithm  # noqa: E501
        """
        pass

    def test_create_algorithm_secret(self):
        """Test case for create_algorithm_secret

        Create a secret for the given algorithm  # noqa: E501
        """
        pass

    def test_delete_algorithm(self):
        """Test case for delete_algorithm

        Delete algorithm  # noqa: E501
        """
        pass

    def test_delete_algorithm_secret(self):
        """Test case for delete_algorithm_secret

        Delete a secret for the given algorithm  # noqa: E501
        """
        pass

    def test_edit_algorithm_secret(self):
        """Test case for edit_algorithm_secret

        Edit a secret for the given algorithm  # noqa: E501
        """
        pass

    def test_get_algorithm(self):
        """Test case for get_algorithm

        Get algorithm metadata  # noqa: E501
        """
        pass

    def test_get_algorithm_build_by_id(self):
        """Test case for get_algorithm_build_by_id

        Get individual algorithm build by ID  # noqa: E501
        """
        pass

    def test_get_algorithm_build_logs(self):
        """Test case for get_algorithm_build_logs

        Get algorithm build logs  # noqa: E501
        """
        pass

    def test_get_algorithm_builds(self):
        """Test case for get_algorithm_builds

        Get algorithm builds  # noqa: E501
        """
        pass

    def test_get_algorithm_by_id(self):
        """Test case for get_algorithm_by_id

        Get algorithm  # noqa: E501
        """
        pass

    def test_get_algorithm_by_id_build_by_id(self):
        """Test case for get_algorithm_by_id_build_by_id

        Get individual algorithm build by ID  # noqa: E501
        """
        pass

    def test_get_algorithm_by_id_build_logs(self):
        """Test case for get_algorithm_by_id_build_logs

        Get algorithm build logs  # noqa: E501
        """
        pass

    def test_get_algorithm_by_id_builds(self):
        """Test case for get_algorithm_by_id_builds

        Get algorithm builds  # noqa: E501
        """
        pass

    def test_get_algorithm_errors_by_algorithm_id(self):
        """Test case for get_algorithm_errors_by_algorithm_id

        Get algorithm errors  # noqa: E501
        """
        pass

    def test_get_algorithm_errors_by_algorithm_name(self):
        """Test case for get_algorithm_errors_by_algorithm_name

        Get algorithm errors  # noqa: E501
        """
        pass

    def test_get_algorithm_errors_by_user_id(self):
        """Test case for get_algorithm_errors_by_user_id

        Get algorithm errors for a given user  # noqa: E501
        """
        pass

    def test_get_algorithm_hash_version(self):
        """Test case for get_algorithm_hash_version

        Get Algorithm by Hash Version  # noqa: E501
        """
        pass

    def test_get_algorithm_scm_connection_status(self):
        """Test case for get_algorithm_scm_connection_status

        Get algorithm SCM connection status  # noqa: E501
        """
        pass

    def test_get_algorithm_secrets(self):
        """Test case for get_algorithm_secrets

        Get all secrets for an Algorithm  # noqa: E501
        """
        pass

    def test_get_algorithm_versions(self):
        """Test case for get_algorithm_versions

        Get algorithm versions  # noqa: E501
        """
        pass

    def test_get_utility_algorithms(self):
        """Test case for get_utility_algorithms

        List of utility algorithms  # noqa: E501
        """
        pass

    def test_list_algorithms_for_user(self):
        """Test case for list_algorithms_for_user

        List algorithms for a user or organization  # noqa: E501
        """
        pass

    def test_publish_algorithm(self):
        """Test case for publish_algorithm

        Publish an algorithm's last successful build  # noqa: E501
        """
        pass

    def test_publish_algorithm_by_id(self):
        """Test case for publish_algorithm_by_id

        Publish an algorithm's last successful build  # noqa: E501
        """
        pass

    def test_receive_algorithm_by_id_scm_repository_event(self):
        """Test case for receive_algorithm_by_id_scm_repository_event

        Receiver of all SCM repository events  # noqa: E501
        """
        pass

    def test_receive_scm_repository_event(self):
        """Test case for receive_scm_repository_event

        Receiver of all SCM repository events  # noqa: E501
        """
        pass

    def test_update_algorithm(self):
        """Test case for update_algorithm

        Update algorithm settings  # noqa: E501
        """
        pass

    def test_update_algorithm_by_id(self):
        """Test case for update_algorithm_by_id

        Update algorithm  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
