"""
    Algorithmia Management APIs

    APIs for managing actions on the Algorithmia platform  # noqa: E501

    The version of the OpenAPI document: 1.5.0
    Contact: support@algorithmia.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import algorithmia_api_client
from algorithmia_api_client.model.invite_code import InviteCode


class TestInviteCode(unittest.TestCase):
    """InviteCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInviteCode(self):
        """Test InviteCode"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InviteCode()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
