"""
    Algorithmia Management APIs

    APIs for managing actions on the Algorithmia platform  # noqa: E501

    The version of the OpenAPI document: 1.5.0
    Contact: support@algorithmia.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import algorithmia_api_client
from algorithmia_api_client.model.build_version_info import BuildVersionInfo
globals()['BuildVersionInfo'] = BuildVersionInfo
from algorithmia_api_client.model.build import Build


class TestBuild(unittest.TestCase):
    """Build unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBuild(self):
        """Test Build"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Build()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
