"""
    Algorithmia Management APIs

    APIs for managing actions on the Algorithmia platform  # noqa: E501

    The version of the OpenAPI document: 1.5.0
    Contact: support@algorithmia.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import algorithmia_api_client
from algorithmia_api_client.model.event_listener_source_type import EventListenerSourceType
globals()['EventListenerSourceType'] = EventListenerSourceType
from algorithmia_api_client.model.event_listener import EventListener


class TestEventListener(unittest.TestCase):
    """EventListener unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEventListener(self):
        """Test EventListener"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EventListener()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
