"""
    Algorithmia Management APIs

    APIs for managing actions on the Algorithmia platform  # noqa: E501

    The version of the OpenAPI document: 1.5.0
    Contact: support@algorithmia.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import algorithmia_api_client
from algorithmia_api_client.model.api_key_type import ApiKeyType
from algorithmia_api_client.model.auth_permissions import AuthPermissions
globals()['ApiKeyType'] = ApiKeyType
globals()['AuthPermissions'] = AuthPermissions
from algorithmia_api_client.model.api_key import ApiKey


class TestApiKey(unittest.TestCase):
    """ApiKey unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiKey(self):
        """Test ApiKey"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiKey()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
