"""
    Algorithmia Management APIs

    APIs for managing actions on the Algorithmia platform  # noqa: E501

    The version of the OpenAPI document: 1.5.0
    Contact: support@algorithmia.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import algorithmia_api_client
from algorithmia_api_client.model.algorithm_secret_create_request import AlgorithmSecretCreateRequest


class TestAlgorithmSecretCreateRequest(unittest.TestCase):
    """AlgorithmSecretCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAlgorithmSecretCreateRequest(self):
        """Test AlgorithmSecretCreateRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AlgorithmSecretCreateRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
