"""
    Algorithmia Management APIs

    APIs for managing actions on the Algorithmia platform  # noqa: E501

    The version of the OpenAPI document: 1.5.0
    Contact: support@algorithmia.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import algorithmia_api_client
from algorithmia_api_client.model.directory_acl import DirectoryAcl
from algorithmia_api_client.model.resource_name import ResourceName
globals()['DirectoryAcl'] = DirectoryAcl
globals()['ResourceName'] = ResourceName
from algorithmia_api_client.model.create_directory_request import CreateDirectoryRequest


class TestCreateDirectoryRequest(unittest.TestCase):
    """CreateDirectoryRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateDirectoryRequest(self):
        """Test CreateDirectoryRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateDirectoryRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
