"""
    Algorithmia Management APIs

    APIs for managing actions on the Algorithmia platform  # noqa: E501

    The version of the OpenAPI document: 1.5.0
    Contact: support@algorithmia.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import algorithmia_api_client
from algorithmia_api_client.model.scm_configuration import ScmConfiguration
from algorithmia_api_client.model.scm_urls import ScmUrls
globals()['ScmConfiguration'] = ScmConfiguration
globals()['ScmUrls'] = ScmUrls
from algorithmia_api_client.model.scm_configuration_response_dto import ScmConfigurationResponseDto


class TestScmConfigurationResponseDto(unittest.TestCase):
    """ScmConfigurationResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScmConfigurationResponseDto(self):
        """Test ScmConfigurationResponseDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ScmConfigurationResponseDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
