"""
    Algorithmia Management APIs

    APIs for managing actions on the Algorithmia platform  # noqa: E501

    The version of the OpenAPI document: 1.5.0
    Contact: support@algorithmia.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import algorithmia_api_client
from algorithmia_api_client.model.event_listener_source_type import EventListenerSourceType


class TestEventListenerSourceType(unittest.TestCase):
    """EventListenerSourceType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEventListenerSourceType(self):
        """Test EventListenerSourceType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EventListenerSourceType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
