"""
    Algorithmia Management APIs

    APIs for managing actions on the Algorithmia platform  # noqa: E501

    The version of the OpenAPI document: 1.5.0
    Contact: support@algorithmia.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import algorithmia_api_client
from algorithmia_api_client.model.scm_bitbucket_configuration import ScmBitbucketConfiguration
from algorithmia_api_client.model.scm_o_auth_configuration import ScmOAuthConfiguration
globals()['ScmBitbucketConfiguration'] = ScmBitbucketConfiguration
globals()['ScmOAuthConfiguration'] = ScmOAuthConfiguration
from algorithmia_api_client.model.scm_configuration import ScmConfiguration


class TestScmConfiguration(unittest.TestCase):
    """ScmConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScmConfiguration(self):
        """Test ScmConfiguration"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ScmConfiguration()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
