"""
    Algorithmia Management APIs

    APIs for managing actions on the Algorithmia platform  # noqa: E501

    The version of the OpenAPI document: 1.5.0
    Contact: support@algorithmia.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import algorithmia_api_client
from algorithmia_api_client.model.scms_secret_token import SCMSSecretToken
from algorithmia_api_client.model.scms_user_pass import SCMSUserPass
globals()['SCMSSecretToken'] = SCMSSecretToken
globals()['SCMSUserPass'] = SCMSUserPass
from algorithmia_api_client.model.scms_user_pass_or_secret_token import SCMSUserPassOrSecretToken


class TestSCMSUserPassOrSecretToken(unittest.TestCase):
    """SCMSUserPassOrSecretToken unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSCMSUserPassOrSecretToken(self):
        """Test SCMSUserPassOrSecretToken"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SCMSUserPassOrSecretToken()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
