name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          # Skip Python 2.7 and 3.5 and PyPy
          CIBW_SKIP: cp27-* cp35-* *-manylinux_i686 pp*
          # gmp already installed on macos runner
          CIBW_BEFORE_ALL_MACOS: python setup.py package_assemble
          CIBW_TEST_COMMAND: python -m regina.test

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
