from aioworkers.core.base import ExecutorEntity as ExecutorEntity, LoggingEntity as LoggingEntity
from aioworkers.net.sender import AbstractSender as AbstractSender
from typing import Any

class SMTP(ExecutorEntity, LoggingEntity, AbstractSender):
    def set_config(self, config: Any) -> None: ...
    def set_context(self, context: Any) -> None: ...
    async def send_message(self, msg: Any) -> None: ...
    async def make_message(self, msg: Any): ...
    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def __aenter__(self): ...
    async def __aexit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...
