[tool.poetry]
name = "komolibs"
version = "0.1.11"
description = ""
authors = ["Khosi Morafo <khosimorafo@yahoo.com>"]

[tool.poetry.dependencies]
python = "^3.7"
aiokafka = "^0.7.1"
certifi = "^2021.5.30"
confluent-kafka = "^1.7.0"
avro = "^1.10.2"
kafka-python = "^2.0.2"
aioredis = "^1.3.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
