language: python

dist: trusty

python:
  - 2.7
  - 3.5
  - 3.6

install:
  - pip install -r requirements.txt
  - pip install .

script:
  - cd test && make html SPHINXOPTS='-W'

notifications:
  email:
    on_failure: change
