
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-18T10:42:35+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "01b2236ab093406f4aa26a05f7dc5240fc59262d",
 "version": "0.9.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
