
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-23T09:30:09-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "17e7a093613f3ff13544a1503aa79dbfc39eef14",
 "version": "2021.06.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
