#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['typeforce']

package_data = \
{'': ['*']}

setup(name='typeforce',
      version='0.2.0',
      description='CLI tool to propagate py.typed into third-party libraries.',
      author='Gram',
      author_email='gram@orsinium.dev',
      url='https://github.com/orsinium-labs/typeforce',
      packages=packages,
      package_data=package_data,
      python_requires='>=3.6',
     )
