[tool.poetry]
name = "pysolaar"
version = "0.8.0"
description = ""
authors = ["Richard Hadden <richard.hadden@oeaw.ac.at>"]

[tool.poetry.dependencies]
python = ">=3.6,<4"
pysolr = "^3.9.0"
solrq = "^1.1.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
icecream = "^2.1.0"
pytest-mock = "^3.5.1"
pytest-sugar = "^0.9.4"
pytest-cov = "^2.11.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
