service: devconfig
period: 15
show-fields:
  - config
apply:
  cumulus:
    version: all
    command: echo '# hostname'; cat /etc/hostname; echo '# interfaces'; cat /etc/network/interfaces; sudo vtysh -c 'show run'; echo '# ports.conf'; cat /etc/ports.conf; echo '# resolv.conf'; cat /etc/resolv.conf
    textfsm:

  eos:
    version: all
    command: show running-config sanitized
    format: text
    textfsm: 

  iosxr:
    version: all
    command: show running-config
    textfsm: 

  nxos:
    version: all
    command: show running-config exclude security
    textfsm: 
      
  junos-qfx:
    version: all
    command: show configuration | except SECRET-DATA
    textfsm: 

  junos-ex:
    copy: junos-qfx

  junos-mx:
    copy: junos-qfx
        
  junos-es:
    copy: junos-qfx

  sonic:
    version: all
    command: show runningconfiguration all
    textfsm:



