[tool.poetry]
name = "aiohttp-sqlalchemy"
version = "0.17.2"
description = "SQLAlchemy 1.4 / 2.0 support for aiohttp."
authors = [
    "Ruslan Ilyasovich Gilfanov <ri.gilfanov@yandex.ru>",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Framework :: AsyncIO",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Topic :: Database",
    "Topic :: Database :: Front-Ends",
    "Topic :: Internet",
    "Topic :: Internet :: WWW/HTTP",
]
keywords = ["aiohttp", "sqlalchemy", "asyncio"]
license = "BSD-3-Clause"
readme = "README.rst"

documentation = "https://aiohttp-sqlalchemy.readthedocs.io/"
repository = "https://github.com/ri-gilfanov/aiohttp-sqlalchemy"

[tool.poetry.dependencies]
python = "^3.7"
aiohttp = "^3.7.4.post0"
SQLAlchemy = "^1.4.18"
aiomysql = { version = ">=0.0.21", optional = true }
aiosqlite = { version = ">=0.17.0", optional = true }
asyncpg = { version = ">=0.23.0", optional = true }

[tool.poetry.extras]
mysql = ["aiomysql"]
postgresql = ["asyncpg"]
sqlite = ["aiosqlite"]

[tool.poetry.dev-dependencies]
aiosqlite = ">=0.17.0"
black = ">=21.6b0"
flake8 = ">=3.9.2"
isort = ">=5.9.1"
mypy = ">=0.910"
pytest = ">=6.2.4"
pytest-cov = ">=2.12.1"
Sphinx = ">=4.0.2"
sphinx_rtd_theme = ">=0.5.2"
types-toml = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py37', 'py38', 'py39']
include = '\.pyi?$'

[tool.isort]
known_first_party = ["aiohttp_sqlalchemy"]
known_third_party = ["aiohttp", "sqlalchemy"]
line_length=88
src_paths = ["aiohttp_sqlalchemy", "examples", "tests"]

[tool.mypy]
files = [
    "aiohttp_sqlalchemy",
    "tests",
]
plugins = "sqlalchemy.ext.mypy.plugin"

[[tool.mypy.overrides]]
module = ['sqlalchemy.*']
ignore_missing_imports = true
