from collections import namedtuple
from enum import Enum
from typing import Any

_corner = namedtuple('Corner', 'top_left top_right bottom_left bottom_right')

class AprilTagFamily(Enum):
    TAG_16h5: Any = ...
    TAG_25h9: Any = ...
    TAG_36h10: Any = ...
    TAG_36h11: Any = ...

class AprilTagDetection:
    def __init__(self, top_right: Any, top_left: Any, bottom_right: Any, bottom_left: Any, tag_id: Any) -> None: ...
    def markup_image(self, image: Any, tag_id: bool = ...): ...
    @property
    def tag_id(self): ...
    @property
    def corners(self): ...

class AprilTagDetector:
    def __init__(self, family: AprilTagFamily) -> None: ...
    def detect(self, image: Any): ...
