
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-22T16:18:36+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "0f5f0839311ce6dba9f1be5c3b3a5fb88185532d",
 "version": "1.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
