[tool.poetry]
name = "linefolio"
version = "1.5.0"
description = "Backtest performance analysis and charting for MoonLine, but with pyfolio."
authors = ["Tim Wedde <timwedde@icloud.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
ipython = "^7.24.1"
matplotlib = "^3.4.2"
numpy = "^1.20.3"
pandas = "^1.2.4"
pytz = "^2021.1"
scipy = "^1.7.0"
scikit-learn = "^0.24.2"
seaborn = "^0.11.1"
empyrical = "^0.5.5"
quantrocket-moonshot = "^2.6.0"

[tool.poetry.dev-dependencies]
pdoc3 = "^0.8.4"
flake8 = "^3.8.3"
pytest = "^6.0.1"
nose-parameterized = "^0.6.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
