[tool.poetry]
name = "rsserpent"
version = "0.1.0a1"
description = "🐍 This snake helps you reconnect the Web, with RSS feeds!"
authors = ["Queensferry <queensferry.me@gmail.com>"]
license = "MIT"

[tool.poetry.extras]
plugin = ["rsserpent-plugin-example"]

[tool.poetry.dependencies]
python = "^3.7"
pydantic = {extras = ["email"], version = "^1.8.2"}
fastapi = "^0.65.2"

[tool.poetry.dev-dependencies]
hypothesis = "^6.14.0"
pre-commit = "^2.13.0"
pytest = "^6.2.4"
pytest-cov = "^2.12.1"
uvicorn = {extras = ["standard"], version = "^0.14.0"}

[tool.black]
include = '\.pyi?$'
target-version = ["py37", "py38", "py39"]

[tool.isort]
balanced_wrapping = true
classes = ["GUID"]
combine_as_imports = true
lines_after_imports = 2
profile = "black"
src_paths = ["rsserpent", "tests"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
