name: test_env_cmip6_preprocessing
channels:
  - conda-forge
dependencies:
  - xarray
  - netcdf4
  - scipy
  - xgcm
  - cftime
  - regionmask
  - xarrayutils
  - pytest-cov
  - pytest-xdist
  - codecov
