# Generated by CommandGenerator on 2021-06-23 20:55:00

from typing import Optional, Tuple
from line_bot_tool.base.commnad import BaseCommand
from . import settings


class HelpCommand(BaseCommand):
    prefixes: Optional[Tuple[str, ...]] = settings.PREFIXES
    cmd: str = 'help'
    description: str = 'Please input here command description.'
