[tool.poetry]
name = "arcane-criteo"
version = "1.0.1"
description = "A client to help us request Criteo API"
authors = ["Arcane <product@arcane.run>"]
packages = [
    { include = "arcane" }
]

[tool.poetry.dependencies]
python = "^3.6"
backoff = "^1.10.0"
criteo-marketing-transition = "^1.0.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
