[tool.poetry]
name = "traductorsqb"
version = "0.0.0"
description = "Traductor de palabras"
authors = ["Santiago Quiñones <lsquinones@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
