import socket
from ..core.base import LoggingEntity as LoggingEntity
from typing import Any, List

class SocketServer(LoggingEntity):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def set_config(self, config: Any) -> None: ...
    def set_context(self, context: Any) -> None: ...
    def bind(self, port: int, host: str=...) -> List[socket.socket]: ...
    def cleanup(self) -> None: ...
