# Generated by Django 3.1.7 on 2021-06-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(editable=False, max_length=255)),
                ('name', models.CharField(editable=False, max_length=255)),
                ('db_table', models.CharField(editable=False, max_length=255)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'django_truncate_table',
                'ordering': ('app', 'name'),
                'unique_together': {('app', 'name')},
            },
        ),
    ]
