[tool.poetry]
name = "finstar"
version = "0.1.0"
description = "Modeling financial time series. WIP!"
authors = ["Alexander Junge <alexander.junge@gmail.com>"]
license = "Apache-2.0"
homepage = "https://github.com/JungeAlexander/finstar"
repository = "https://github.com/JungeAlexander/finstar/tree/main/src"
readme = "README.md"
packages = [
    { include = "finstar", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.9"
yfinance = "^0.1.59"
altair = "^4.1.0"
pandas = "^1.2.4"
numpy = "^1.20.3"

[tool.poetry.dev-dependencies]
jupyterlab = "^3.0.16"
pytest = "^6.2.4"
black = "^21.6b0"
pre-commit = "^2.13.0"
mkdocs-material = "^7.1.8"
mkdocs = "^1.2.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
