
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-08T16:07:47+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e26245effab3869ce2fbdf7f5bb12728cc30b42a",
 "version": "0.21.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
