from .. import utils as utils
from ..core.formatter import FormattedEntity as FormattedEntity
from .base import Worker as Worker
from typing import Any

class Subprocess(FormattedEntity, Worker):
    params: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    create_subprocess: Any = ...
    async def init(self): ...
    @property
    def process(self): ...
    def make_command(self, value: Any): ...
    async def run_cmd(self, *args: Any, **kwargs: Any): ...
    async def work(self): ...
    async def start(self): ...
    async def stop(self, force: bool = ...) -> None: ...
