from .base import Worker as Worker
from typing import Any

logger: Any

class Supervisor(Worker):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, item: Any): ...
    def __getitem__(self, item: Any): ...
    async def init(self): ...
    def __call__(self, *args: Any, **kwargs: Any): ...
    def get_child_config(self, *args: Any, **kwargs: Any): ...
    def create_child(self, *args: Any, **kwargs: Any): ...
    async def get(self): ...
    async def put(self, *args: Any, **kwargs: Any): ...
    async def work(self): ...
    async def stop(self, force: bool = ...): ...
    async def status(self): ...
