
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-23T12:07:45+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "342d8c9358c358cbc5caee1b0cee1d8c64ec3d0e",
 "version": "0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
