[tool.poetry]
name = "haveibeenpwned-asyncio"
version = "0.0.4"
description = "Asyncio and aiohttp based library and CLI to connect to haveibeenpwned"
authors = ["Christo Goosen <christogoosen@gmail.com>"]
license = "MIT"
packages = [
    { include = "haveibeenpwned_asyncio" },
    { include = "haveibeenpwned_asyncio/*.py" },
    { include = "haveibeenpwned_asyncio/**/*.py" },
]

[tool.poetry.dependencies]
python = "^3.6"
aiohttp = "^3.7.4"
click = "^8.0.1"
aiohttp-retry = "^2.4.0"


[tool.poetry.dev-dependencies]
pytest = "^6.2.1"
pytest-runner = "^5.2"
bandit = "^1.7.0"
black = "^20.8b1"
flake8 = "^3.8.4"
twine = "^3.3.0"
setuptools = "^51.3.3"
python-dateutil = "^2.8.1"
pytest-cov = "^2.12.1"
nose = "^1.3.7"
trio = "^0.18.0"
pytest-asyncio = "^0.15.1"
aresponses = "^2.1.4"
pytest-aiohttp = "^0.3.0"
pytest-mock = "^3.6.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

