
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-23T16:27:46-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "15f8667be2b5dcbc44fd1f2b7b2fee5a8d27089b",
 "version": "v0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
