#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['apio', 'apio.commands', 'apio.managers']

package_data = \
{'': ['*'], 'apio': ['resources/*', 'resources/ecp5/*', 'resources/ice40/*']}

install_requires = \
['pyjwt >=1.5.3,<2']

entry_points = \
{'console_scripts': ['apio = apio.__main__:cli']}

setup(name='apio',
      version='0.6.2',
      description='Open source ecosystem for open FPGA boards',
      author='Jesus Arroyo',
      author_email='jesus.jkhlg@gmail.com ',
      url='https://github.com/FPGAwars/apio',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      entry_points=entry_points,
      python_requires='>=3.7',
     )
