# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ValueTupleInt32Int32(Model):
    """ValueTupleInt32Int32.

    :param item1:
    :type item1: int
    :param item2:
    :type item2: int
    """

    _attribute_map = {
        'item1': {'key': 'Item1', 'type': 'int'},
        'item2': {'key': 'Item2', 'type': 'int'},
    }

    def __init__(self, **kwargs):
        super(ValueTupleInt32Int32, self).__init__(**kwargs)
        self.item1 = kwargs.get('item1', None)
        self.item2 = kwargs.get('item2', None)
