[build-system]
requires = ["setuptools", "wheel"]

[tool.pylint.'MESSAGES CONTROL']
disable = "line-too-long,invalid-name,too-few-public-methods,too-many-instance-attributes,too-many-arguments,missing-docstring"
output-format = "text"
reports = "no"
