
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-25T15:18:42-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "7c705c4257de170d98094dd57f5851c9772477fa",
 "version": "0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
