[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "flask_regiment"
author = "regiment.tech"
author-email = "support@regiment.tech"
home-page = "https://www.regiment.tech/"
classifiers = [ "License :: OSI Approved :: MIT License",]
requires-python = ">=3.7"
requires = ["flask", "requests", "blinker"]
