
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-22T11:56:21-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "ac35e0f8104baaccfb44f98b67a48ee359069316",
 "version": "2021.06.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
