from typing import Any

def ssd_post_process(results: Any, image: Any, confidence_level: Any): ...
def ssd_flat_post_process(results: Any, image: Any, confidence_level: Any): ...
def ssd_trt_post_process(predictions: Any, image: Any, confidence_level: Any): ...
def yolo_post_process(detections: Any, image: Any, confidence_level: Any, overlap_threshold: Any): ...
def yolo_trt_post_process(results: Any, image: Any, confidence_level: Any, overlap_threshold: Any): ...
