
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-24T21:56:35-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "638edd85bfffe154180e0b861c0dc5c7ad5754fc",
 "version": "0.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
