
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-22T21:12:41+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "7f6662caea8ff4c803b5410e5145d14fbc314433",
 "version": "0.9.0+6.g7f6662c"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
