# Generated by Django 2.2.5 on 2021-04-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OtpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(max_length=100)),
                ('is_valid', models.BooleanField(default=True)),
                ('expires_on', models.DateTimeField()),
            ],
        ),
    ]
