# Generated by Django 2.2.5 on 2021-04-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpmodel',
            name='can_send_otp_after',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='otpmodel',
            name='remaining_attempts',
            field=models.IntegerField(default=5),
        ),
    ]
