[tool.poetry]
name = "leapcli"
version = "0.1.0"
description = "Tensorleap CLI"
authors = ["Assaf Lavie <assaf.lavie@tensorleap.ai>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
docopt = "^0.6.2"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
leap = "leapcli.cli:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

