#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['pyphen']

package_data = \
{'': ['*'], 'pyphen': ['dictionaries/*']}

extras_require = \
{'test': ['pytest',
          'pytest-cov',
          'pytest-flake8',
          'pytest-isort',
          'coverage[toml]']}

setup(name='pyphen',
      version='0.11.0',
      description='Pure Python module to hyphenate text',
      author=None,
      author_email='Guillaume Ayoub <contact@courtbouillon.org>',
      url=None,
      packages=packages,
      package_data=package_data,
      extras_require=extras_require,
      python_requires='>=3.6',
     )
