#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['snapcastcontrol',
 'snapcastcontrol.control',
 'snapcastcontrol.control.library']

package_data = \
{'': ['*']}

setup(name='snapcastcontrol',
      version='0.1.0',
      description='snapcastcontrol',
      author='Poul Spang',
      author_email=None,
      url='https://github.com/poulsp/python-snapcastcontrol',
      packages=packages,
      package_data=package_data,
      python_requires='>=3.7',
     )
