# Copyright (c) 2020, Anders Lervik.
# Distributed under the LGPLv2.1+ License. See LICENSE for more info.
"""Version information for gpxplotter.

This file is generated by gpxplotter (``setup_version.py``).
"""
SHORT_VERSION = '0.2.9'
VERSION = '0.2.9'
FULL_VERSION = '0.2.9'
GIT_REVISION = 'd7f01f9f21904e5df35d99f99ded9f04ea92a8b3'
GIT_VERSION = '0.2.9'
RELEASE = True

if not RELEASE:
    VERSION = GIT_VERSION
