
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-24T11:51:59-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "7c2d8ea1de127b5c25fbe03015c461f8521e8ce2",
 "version": "4.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
