[build-system]
requires = [
    "setuptools>=42",
    "numpy>=1.16.2",
    "seaborn>=0.9.0",
    "matplotlib>=3.0.3",
    "scikit-learn>=0.20.3",
    "lifetimes==0.10.1",
    "wheel"
]
build-backend = "setuptools.build_meta"