
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-22T17:57:14+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "08bd8066c89af0248ba2eaf98800858c7d939056",
 "version": "0.1.1.22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
