[tool.poetry]
name = "vag"
version = "0.1.55"
description = "vagrant utility cli tool"
authors = ["Seven Tella <7onetella@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
Click = "^7.1.2"
untangle = "^1.1.1"
jinja2 = "^3.0.1"
requests = "^2.25.1"
pyyaml = "^5.4.1"
sqlalchemy = "^1.4.15"
pylint = "^2.8.2"
giteapy = "^1.0.8"
Flask = "^2.0.1"
oauthlib = "^3.1.1"
Flask-Login = "^0.5.0"
pyOpenSSL = "^20.0.1"
random-username = "^1.0.2"
random-password-generator = "^2.1.2"
cryptography = "^3.4.7"
jenkinsapi = "^0.3.11"
psycopg2 = "^2.9.1"

[tool.poetry.scripts]
vag = "vag.console.application:main"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
