#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['mdformat_myst']

package_data = \
{'': ['*']}

install_requires = \
['mdformat >=0.7.0,<0.8.0',
 'mdit-py-plugins >=0.2.7,<0.3.0',
 'mdformat-tables >=0.4.0',
 'mdformat-frontmatter >=0.3.2',
 'ruamel.yaml >=0.16.0']

extras_require = \
{'dev': ['pre-commit'], 'test': ['pytest', 'coverage', 'pytest-cov']}

entry_points = \
{'mdformat.parser_extension': ['myst = mdformat_myst.plugin']}

setup(name='mdformat_myst',
      version='0.1.4',
      description='Mdformat plugin for MyST compatibility.',
      author='Taneli Hukkinen',
      author_email='executablebooks@gmail.com',
      url='https://github.com/hukkinj1/mdformat-myst',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      entry_points=entry_points,
      python_requires='>=3.7',
     )
