
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-20T18:41:50-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "b179a6e1036b63179800bed2a17e51cc46e9b5b1",
 "version": "0.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
