from typing import Any, Optional

class CommandNotFound(RuntimeError): ...

def kwargs_from_argv(params: Any, ns: Any, argv: Any): ...
def run(cmd: Any, context: Any, loop: Optional[Any] = ..., ns: Optional[Any] = ..., argv: Optional[Any] = ...): ...
