[tool.poetry]
name = "tinybee"
version = "0.1.5"
description = "A tiny aligner for dualtext alignment"
authors = ["ffreemt"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/ffreemt/tinybee-aligner"

[tool.poetry.dependencies]
python = "^3.7"
logzero = "^1.6.3"
polyglot = "^16.7.4"
sentence-splitter = "^1.4"
more-itertools = "^8.6.0"
joblib = "^1.0.0"
cchardet = "^2.1.7"
statsmodels = "^0.12.1"
httpx = "^0.17.1"
pyicu = "2.6"
pycld2 = "^0.41"
morfessor = "^2.0.6"
halo = "^0.0.31"
alive-progress = "^1.6.2"
fetch-embed = "^0.1.3"
absl-py = "^0.12.0"
matplotlib = "^3.4.1"
seaborn = "^0.11.1"
sklearn = "^0.0"
fasttext = "^0.9.2"
simplemma = "^0.3.0"

[tool.poe.executor]
type = "poetry"

[tool.poe.tasks]
test = "pytest tests"
build = "poetry build"
_publish = "poetry publish"
release = ["test", "build", "_publish"]
lint = { cmd = "pylint tinybee" }
# test1 = {cmd = "nodemon -w tests -w tinybee -x pytest tests"}
# typing = {cmd = "C:\Users\mike\AppData\Roaming\npm\pyright"}
format = "black tests tinybee"
tunnel = {cmd ="ssh -CN acone3 -L 9091:127.0.0.1:9091"}

[tool.poetry.dev-dependencies]
pytest = "^5.2"
ipython = "^7.21.0"
flake8 = "^3.8.4"
pylint = "^2.7.4"
tbump = "^6.3.1"
poethepoet = "^0.10.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
