#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['scrapy_item_pipelines']

package_data = \
{'': ['*']}

install_requires = \
['confluent-kafka']

extras_require = \
{'dev': ['flake8']}

setup(name='scrapy-item-pipelines',
      version='0.2',
      description='Collection of reusable scrapy item pipelines',
      author='Kasun Herath',
      author_email='kasunh01@gmail.com',
      url='https://github.com/singletonlabs/scrapy-item-pipelines',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='>=3.6',
     )
