from unittest_reinvent.scoring_tests.scoring_functions.test_custom_sum import Test_custom_sum
from unittest_reinvent.scoring_tests.scoring_functions.test_custom_sum_combined_distance_and_similarity import \
    Test_combined_distance_and_similarity
from unittest_reinvent.scoring_tests.scoring_functions.test_custom_sum_custom_alerts import \
    Test_custom_alerts_with_user_alerts, Test_custom_alerts_with_default_alerts
from unittest_reinvent.scoring_tests.scoring_functions.test_custom_sum_jaccard_distance import Test_jaccard_distance
from unittest_reinvent.scoring_tests.scoring_functions.test_custom_sum_matching_substructure import \
    Test_matching_substructures_not_provided, Test_matching_substructures, Test_invalid_matching_substructure
from unittest_reinvent.scoring_tests.scoring_functions.test_custom_sum_qed_score import Test_custom_sum_qed_score
from unittest_reinvent.scoring_tests.scoring_functions.test_custom_sum_tanimoto_similarity import \
    Test_tanimoto_similarity
from unittest_reinvent.scoring_tests.scoring_functions.test_parallel_additive import Test_parallel_additive
from unittest_reinvent.scoring_tests.scoring_functions.test_parallel_primary_multiplicative import \
    Test_parallel_primary_multiplicative_function
from unittest_reinvent.scoring_tests.scoring_functions.test_parallel_product import Test_parallel_product
from unittest_reinvent.scoring_tests.scoring_functions.test_parallel_scoring_function_factory import \
    Test_parallel_scoring_function_factory
from unittest_reinvent.scoring_tests.scoring_functions.test_parallel_selectivity_multiplicative import \
    Test_parallel_selectivity_multiplicative_function
from unittest_reinvent.scoring_tests.scoring_functions.test_primary_multiplicative import \
    Test_primary_mult_with_alert_no_sigm_trans, Test_primary_mult_with_no_activity, \
    Test_primary_mult_with_no_activity_2, Test_primary_mult_with_prediction_classification_and_regression_alert, \
    Test_primary_multiplicative_function, Test_primary_multiplicative_with_alert
from unittest_reinvent.scoring_tests.scoring_functions.test_primary_multiplicative_with_desirability_component import \
    Test_primary_multiplicative_with_desirability_component
from unittest_reinvent.scoring_tests.scoring_functions.test_product import Test_product
from unittest_reinvent.scoring_tests.scoring_functions.test_score_transformations import Test_score_transformations
from unittest_reinvent.scoring_tests.scoring_functions.test_scoring_function_factory import \
    Test_scoring_function_factory
from unittest_reinvent.scoring_tests.scoring_functions.test_selectivity_multiplicative import \
    Test_selectivity_multiplicative_function, Test_selectivity_multiplicative_function_with_predictive_property, \
    Test_selectivity_multiplicative_function_with_predictive_property_and_alert, \
    Test_selectivity_multiplicative_function_with_predictive_property_no_sigm_trans
from unittest_reinvent.scoring_tests.scoring_functions.test_selectivity_multiplicative_double_sigmoid import \
    Test_desirability_multiplicative_function, Test_selectivity_function_with_double_sigmoid, \
    Test_special_desirability_multiplicative_function
