
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-19T08:57:18-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "b21e43092889c5c5c91ca092ada1fac20fb75d3c",
 "version": "2.0.0a3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
