[tool.poetry]
name = "rpi-flash"
version = "0.1.0"
description = ""
authors = ["Jono Hill <jono@hillnz.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pydantic = "^1.8.2"
requests = "^2.25.1"
typer = "^0.3.2"
humanize = "^3.9.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
