
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-17T18:15:09+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "43a4e3c05848edbe24432122b8f5585fb80642cd",
 "version": "0.9.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
