
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-19T21:16:50+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "56dd3e22eb66c4eb8326c2fa9e18dc473331fc06",
 "version": "1.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
