[tool.poetry]
name = "essencia_pack"
version = "0.1.5"
description = ""
authors = ["arantesdv <arantesdv@me.com>"]

[tool.poetry.dependencies]
python = "^3.7"
python-multipart = "^0.0.5"
starlette = "^0.14.2"
pydantic = "^1.8.1"
flama = "^0.16.0"
uvicorn = "^0.13.4"
apispec = "^4.4.0"
PyYAML = "^5.4.1"
deta = "^0.7"
python-dotenv = "^0.17.0"
requests = "^2.25.1"
Jinja2 = "^2.11.3"
aiofiles = "^0.6.0"
itsdangerous = "^1.1.0"
graphene = "^2.1.8"
SQLAlchemy = "1.3.9"
databases = "^0.4.3"
aiosqlite = "^0.17.0"
python-forge = "^18.6.0"
httpx = "^0.17.1"
orm = "^0.1.5"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
