
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-20T02:36:34+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "aa46aae6aa47dabefd13f8bed7d2bf35137eb5d2",
 "version": "0.6.dev2125"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
