
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-23T12:51:31-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "0b10cffd6d092639bacfe8cd4e5cae34b7006cbf",
 "version": "0.1.0a18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
