---
- name: my postgresql instances
  hosts: localhost
  tasks:
    - name: production instance
      postgresql_instance:
        name: prod
        state: started
        port: 5433
        ssl: true
        configuration:
          max_connections: 100
          shared_buffers: 1GB
          unix_socket_directories: /tmp

    - name: pre-production instance
      postgresql_instance:
        name: preprod
        port: 5434
        state: started
        configuration:
          unix_socket_directories: /tmp
        prometheus_port: 9188

    - name: dev instance, not running at the moment
      postgresql_instance:
        name: dev
        port: 5444
        state: stopped
        configuration:
          unix_socket_directories: /tmp
        prometheus_port: 9189
