from typing import Any

SIZE: Any
logger: Any

def import_name(stref: str) -> Any: ...
def import_uri(obj: Any): ...
def module_path(str_module: Any, return_str: bool = ...): ...
def method_replicate_result(key: Any): ...
def monkey_close(loop: Any) -> None: ...
def try_read(n: Any, fd: Any, timeout: int = ...): ...
def load_from_fd(fd: Any): ...
def dump_to_fd(fd: Any, data: Any) -> None: ...
def mapping_repr(*maps: Any, indent: int = ..., **kwargs: Any): ...
