[tool.poetry]
name = "potaru"
version = "0.1.0"
description = ""
authors = ["Alon Gubkin <alon.gubkin@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.0.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
potaru = "src.potaru.__main__:cli"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
