
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-22T10:06:50+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "69214578572a4b4213f794c7a7dbd995139098b3",
 "version": "v3.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
