[tool.poetry]
name = "trax-extra-activation"
version = "0.0.2" # poetry-dynamic-versioning
description = "Extra activation functions for Trax"
authors = ["Catminusminus <getomya@svk.jp>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/Catminusminus/trax-extra-activation"
repository = "https://github.com/Catminusminus/trax-extra-activation"
keywords = ["trax", "jax", "machine learning"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pysen = {version = "0.9.1", extras = ["lint"]}
pysen-ls = ">=0.1.0"

[tool.poetry-dynamic-versioning]
enable = false
style = "pep440"

[tool.pysen]
version = "0.9"

[tool.pysen.lint]
enable_black = true
enable_flake8 = true
enable_isort = true
enable_mypy = true
mypy_preset = "strict"
line_length = 88
py_version = "py37"
[[tool.pysen.lint.mypy_targets]]
  paths = ["."]

[tool.pysen.lint.source]
  excludes = [".venv/"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
