[tool.poetry]
name = "snapsheets"
version = "0.5.7"
description = "Getting tired of downloading Google Spreadsheets one by one from the browser ?"
authors = ["shotakaha <shotakaha+py@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://shotakaha.gitlab.io/snapsheets/"
repository = "https://gitlab.com/shotakaha/snapsheets"
keywords=["wget", "googlesheet"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: Japanese",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    ]

[tool.poetry.scripts]
snapsheets ="snapsheets.core:cli"


[tool.poetry.dependencies]
python = "^3.7"
PyYAML = "^5.4.1"
Deprecated = "^1.2.12"
icecream = "^2.1.0"
pendulum = "^2.1.2"
toml = "^0.10.2"
docopt = "^0.6.2"

[tool.poetry.dev-dependencies]
commitizen = "^2.17.0"
pytest = "^6.2.2"
black = "^20.8b1"
Sphinx = "^3.5.3"
sphinx-rtd-theme = "^0.5.1"
pysen = {version = "^0.9.1", extras = ["lint"]}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.5.7"
tag_format = "v$version"

[tool.pysen]
version = "0.9"

[tool.pysen.lint]
enable_black = true
enable_flake8 = false
enable_isort = true
enable_mypy = true
mypy_preset = "strict"
line_length = 88
py_version = "py38"
[[tool.pysen.lint.mypy_targets]]
    paths = ["."]