[tool.poetry]
name = "euporie"
version = "0.1.16"
description = "Euporie is a text-based user interface for running and editing Jupyter notebooks"
authors = ["Josiah Outram Halstead <josiah@halstead.email>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/joouha/euporie"
keywords = ["jupyter", "ipython", "markdown", "terminal", "notebook"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Programming Language :: Python :: 3.8",
    "Topic :: Scientific/Engineering",
]

[tool.poetry.dependencies]
python = "^3.8"
rich = "^10.1.0"
nbformat = "^5.1.3"
img2unicode = {version = "^0.1a7", optional = true}
prompt-toolkit = "^3.0.18"
timg = {version = "^1.1.5", optional = true}
mtable = {version = "^0.1.10", optional = true}
html5lib = {version = "^1.1", optional = true}
Pillow = "^8.2.0"
jupyter-client = "6.1.12"
jsonschema = "^3.2.0"
appdirs = "^1.4.4"
pyperclip = "^1.8.2"

[tool.poetry.extras]
html-mtable = ["mtable", "html5lib"]
images-timg = ["timg"]
images-img2unicode = ["img2unicode"]

[tool.poetry.dev-dependencies]
pytest = "^5.2"
isort = "^5.8.0"
flake8 = "^3.9.1"
black = "^21.5b0"
poetry-publish = "^0.4.1"
flake8-black = "^0.2.1"
flake8-bugbear = "^21.4.3"
flake8-bandit = "^2.1.2"
flake8-annotations = "^2.6.2"
flake8-docstrings = "^1.6.0"
mypy = "^0.812"
flake8-isort = "^4.0.0"
darglint = "^1.8.0"

[tool.poetry.scripts]
euporie = 'euporie.app:App.launch'

[tool.isort]
profile = "black"
multi_line_output = 3

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
