[build-system]
# Minimum requirements for the build system to execute.
requires = [
    "setuptools>=42",
    "wheel",
    "pyyaml",
    "pytest",
    "pytest-mock"
]
build-backend = 'setuptools.build_meta'