[tool.poetry]
name = "zip2kafka"
version = "0.1.0"
description = "Package a zip and push it to kafka (and back!)"
authors = ["Dmitri Gvozdev <dmitrigvozdev94@gmail.com>"]

#packages = [
#    { include = "main.py", from = "src" },
#]


[tool.poetry.scripts]
zip2kafka = "zip2kafka.main:app"

[tool.poetry.dependencies]
python = "^3.8"
typer = "^0.3.2"
confluent-kafka = "^1.7.0"
loguru = "^0.5.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

