
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-25T14:02:32+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "5a17167b42c8ec80a25ebb32c8f9c2e32ec07568",
 "version": "0.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
