[tool.poetry]
name = "trial-hello"
version = "0.1.1"
description = ""
authors = ["Bhuwan Bhatt <bhattbhuwan13@outlook.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
trial_hello = 'trial_hello.console:main'
