# -*- coding: utf-8 -*-
#
# Copyright (c) 2021 Nitric Technologies Pty Ltd.
#
# This file is part of Nitric Python 3 SDK.
# See https://github.com/nitrictech/python-sdk for further info.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: storage/v1/storage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='storage/v1/storage.proto',
  package='nitric.storage.v1',
  syntax='proto3',
  serialized_options=b'\n\032io.nitric.proto.storage.v1B\010StoragesP\001Z\014nitric/v1;v1\252\002\027Nitric.Proto.Storage.v1\312\002\027Nitric\\Proto\\Storage\\V1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18storage/v1/storage.proto\x12\x11nitric.storage.v1\"E\n\x13StorageWriteRequest\x12\x13\n\x0b\x62ucket_name\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\x0c\"\x16\n\x14StorageWriteResponse\"6\n\x12StorageReadRequest\x12\x13\n\x0b\x62ucket_name\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\"#\n\x13StorageReadResponse\x12\x0c\n\x04\x62ody\x18\x01 \x01(\x0c\"8\n\x14StorageDeleteRequest\x12\x13\n\x0b\x62ucket_name\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\"\x17\n\x15StorageDeleteResponse2\x97\x02\n\x07Storage\x12U\n\x04Read\x12%.nitric.storage.v1.StorageReadRequest\x1a&.nitric.storage.v1.StorageReadResponse\x12X\n\x05Write\x12&.nitric.storage.v1.StorageWriteRequest\x1a\'.nitric.storage.v1.StorageWriteResponse\x12[\n\x06\x44\x65lete\x12\'.nitric.storage.v1.StorageDeleteRequest\x1a(.nitric.storage.v1.StorageDeleteResponseBj\n\x1aio.nitric.proto.storage.v1B\x08StoragesP\x01Z\x0cnitric/v1;v1\xaa\x02\x17Nitric.Proto.Storage.v1\xca\x02\x17Nitric\\Proto\\Storage\\V1b\x06proto3'
)




_STORAGEWRITEREQUEST = _descriptor.Descriptor(
  name='StorageWriteRequest',
  full_name='nitric.storage.v1.StorageWriteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bucket_name', full_name='nitric.storage.v1.StorageWriteRequest.bucket_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key', full_name='nitric.storage.v1.StorageWriteRequest.key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='body', full_name='nitric.storage.v1.StorageWriteRequest.body', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=116,
)


_STORAGEWRITERESPONSE = _descriptor.Descriptor(
  name='StorageWriteResponse',
  full_name='nitric.storage.v1.StorageWriteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=140,
)


_STORAGEREADREQUEST = _descriptor.Descriptor(
  name='StorageReadRequest',
  full_name='nitric.storage.v1.StorageReadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bucket_name', full_name='nitric.storage.v1.StorageReadRequest.bucket_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key', full_name='nitric.storage.v1.StorageReadRequest.key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=196,
)


_STORAGEREADRESPONSE = _descriptor.Descriptor(
  name='StorageReadResponse',
  full_name='nitric.storage.v1.StorageReadResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='body', full_name='nitric.storage.v1.StorageReadResponse.body', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=233,
)


_STORAGEDELETEREQUEST = _descriptor.Descriptor(
  name='StorageDeleteRequest',
  full_name='nitric.storage.v1.StorageDeleteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bucket_name', full_name='nitric.storage.v1.StorageDeleteRequest.bucket_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key', full_name='nitric.storage.v1.StorageDeleteRequest.key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=291,
)


_STORAGEDELETERESPONSE = _descriptor.Descriptor(
  name='StorageDeleteResponse',
  full_name='nitric.storage.v1.StorageDeleteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=293,
  serialized_end=316,
)

DESCRIPTOR.message_types_by_name['StorageWriteRequest'] = _STORAGEWRITEREQUEST
DESCRIPTOR.message_types_by_name['StorageWriteResponse'] = _STORAGEWRITERESPONSE
DESCRIPTOR.message_types_by_name['StorageReadRequest'] = _STORAGEREADREQUEST
DESCRIPTOR.message_types_by_name['StorageReadResponse'] = _STORAGEREADRESPONSE
DESCRIPTOR.message_types_by_name['StorageDeleteRequest'] = _STORAGEDELETEREQUEST
DESCRIPTOR.message_types_by_name['StorageDeleteResponse'] = _STORAGEDELETERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StorageWriteRequest = _reflection.GeneratedProtocolMessageType('StorageWriteRequest', (_message.Message,), {
  'DESCRIPTOR' : _STORAGEWRITEREQUEST,
  '__module__' : 'storage.v1.storage_pb2'
  # @@protoc_insertion_point(class_scope:nitric.storage.v1.StorageWriteRequest)
  })
_sym_db.RegisterMessage(StorageWriteRequest)

StorageWriteResponse = _reflection.GeneratedProtocolMessageType('StorageWriteResponse', (_message.Message,), {
  'DESCRIPTOR' : _STORAGEWRITERESPONSE,
  '__module__' : 'storage.v1.storage_pb2'
  # @@protoc_insertion_point(class_scope:nitric.storage.v1.StorageWriteResponse)
  })
_sym_db.RegisterMessage(StorageWriteResponse)

StorageReadRequest = _reflection.GeneratedProtocolMessageType('StorageReadRequest', (_message.Message,), {
  'DESCRIPTOR' : _STORAGEREADREQUEST,
  '__module__' : 'storage.v1.storage_pb2'
  # @@protoc_insertion_point(class_scope:nitric.storage.v1.StorageReadRequest)
  })
_sym_db.RegisterMessage(StorageReadRequest)

StorageReadResponse = _reflection.GeneratedProtocolMessageType('StorageReadResponse', (_message.Message,), {
  'DESCRIPTOR' : _STORAGEREADRESPONSE,
  '__module__' : 'storage.v1.storage_pb2'
  # @@protoc_insertion_point(class_scope:nitric.storage.v1.StorageReadResponse)
  })
_sym_db.RegisterMessage(StorageReadResponse)

StorageDeleteRequest = _reflection.GeneratedProtocolMessageType('StorageDeleteRequest', (_message.Message,), {
  'DESCRIPTOR' : _STORAGEDELETEREQUEST,
  '__module__' : 'storage.v1.storage_pb2'
  # @@protoc_insertion_point(class_scope:nitric.storage.v1.StorageDeleteRequest)
  })
_sym_db.RegisterMessage(StorageDeleteRequest)

StorageDeleteResponse = _reflection.GeneratedProtocolMessageType('StorageDeleteResponse', (_message.Message,), {
  'DESCRIPTOR' : _STORAGEDELETERESPONSE,
  '__module__' : 'storage.v1.storage_pb2'
  # @@protoc_insertion_point(class_scope:nitric.storage.v1.StorageDeleteResponse)
  })
_sym_db.RegisterMessage(StorageDeleteResponse)


DESCRIPTOR._options = None

_STORAGE = _descriptor.ServiceDescriptor(
  name='Storage',
  full_name='nitric.storage.v1.Storage',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=319,
  serialized_end=598,
  methods=[
  _descriptor.MethodDescriptor(
    name='Read',
    full_name='nitric.storage.v1.Storage.Read',
    index=0,
    containing_service=None,
    input_type=_STORAGEREADREQUEST,
    output_type=_STORAGEREADRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Write',
    full_name='nitric.storage.v1.Storage.Write',
    index=1,
    containing_service=None,
    input_type=_STORAGEWRITEREQUEST,
    output_type=_STORAGEWRITERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Delete',
    full_name='nitric.storage.v1.Storage.Delete',
    index=2,
    containing_service=None,
    input_type=_STORAGEDELETEREQUEST,
    output_type=_STORAGEDELETERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_STORAGE)

DESCRIPTOR.services_by_name['Storage'] = _STORAGE

# @@protoc_insertion_point(module_scope)
