[tool.poetry]
name = "denver_api"
version = "3.0.1a0"
description = "Denver API for python full-stack development"
authors = ["xcodz-dot <71920621+xcodz-dot@users.noreply.github.com>"]
license = "MIT"
readme="README.md"
homepage="https://github.com/xcodz-dot/denver-api"
documentation="https://xcodz-dot.github.io/denver"
keywords=[
    "deneverapi",
    "denver",
    "denver-api",
    "python",
    "full-stack"
]
classifiers = [
    "Programming Language :: Python :: 3.6",
    "Operating System :: OS Independent"
]
packages=[
    { include="denverapi" }
]


[tool.poetry.dependencies]
python = "^3.6"
setuptools = ">=50"
requests = ">=2.25.1"
playsound = ">=1.2.2"
pygame = {version=">=2.0.1", optional=true}
packaging = ">=20.9"
pip = ">=21"
pycryptodomex = {version=">=3.10.1", optional=true}
ansiwrap = ">=0.8.4"
colorama = ">=0.4.4"

[tool.poetry.extras]
gui-tools = ["pygame"]
encryption = ["pycryptodomex"]

[tool.poetry.scripts]
rmrdir = "denverapi.clineutils.rmrdir:main"
rmr = "denverapi.clineutils.rmr:main"
bdtpserver = "denverapi.tools.bdtpserver:main"
cryptify = "denverapi.tools.cryptify:main [encryption]"
denverdb = "denverapi.database:cli"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
