
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-23T09:05:14+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "841dc254c486709ab901f6215654d231e5767639",
 "version": "0.7.post1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
