[tool]
[tool.poetry]
name = "techlib-nr-theses"
version = "1.0.0a11"
description = "Czech National Repository theses data model."
license = "MIT"
keywords = ["Czech", "Nation", "Repository", "Invenio", "theses"]
classifiers = ["Environment :: Web Environment", "Intended Audience :: Developers", "License :: OSI Approved :: MIT License", "Operating System :: OS Independent", "Programming Language :: Python", "Topic :: Internet :: WWW/HTTP :: Dynamic Content", "Topic :: Software Development :: Libraries :: Python Modules", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.7", "Development Status :: 3 - Alpha"]
authors = ["Daniel Kopecký <Daniel.Kopecky@techlib.cz>", "Denys Chaplyhin <chaplyhd@vscht.cz>"]
readme = "README.md"
packages = [{include='nr_theses'}]


[tool.poetry.dependencies]
python = "^3.8"
techlib-nr-common = "^3.0.0a48"
techlib-nr-theses-metadata  = "^1.0.0a13"
oarepo = "^3.3.59"

[tool.poetry.dev-dependencies]
oarepo = "^3.3"
oarepo-mapping-includes = "<=1.2.0"
oarepo-invenio-model = "^2.0.1"
oarepo-multilingual = "^2.2.0"
oarepo-taxonomies = "^3.0.0a4"
oarepo-records-draft = "^5.0.0a7"
oarepo-references = "^1.9.0"
oarepo-validate = "^1.2.8"
pytest = "^5.0.0"
pytest-cov = "^2.10.1"
pytest-runner = "^5.2"
oarepo-fsm = "^1.5.0"
oarepo-communities = "^2.0"
techlib-nr-generic = "^1.0.0-alpha.1"

[tool.poetry.plugins]
[tool.poetry.plugins."invenio_base.apps"]
'theses' = 'nr_theses:NRTheses'

[tool.poetry.plugins."invenio_base.api_apps"]
'theses' = 'nr_theses:NRTheses'

[tool.poetry.plugins.'invenio_jsonschemas.schemas']
'nr_theses' = 'nr_theses.jsonschemas'

[tool.poetry.plugins.'invenio_search.mappings']
'nr_theses' = 'nr_theses.mappings'

[tool.poetry.plugins.'oarepo_mapping_includes']
'nr_theses' = 'nr_theses.mapping_includes'

[tool.poetry.plugins."invenio_pidstore.minters"]
'nr_theses' = 'nr_theses.minters:nr_theses_id_minter'

[tool.poetry.plugins."invenio_pidstore.fetchers"]
'nr_theses' = 'nr_theses.fetchers:nr_theses_id_fetcher'
