[tool.poetry]
name = "disable_print"
version = "0.1.0"
description = ""
authors = ["Fab4key"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
