
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-18T10:55:53+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "011718b77acd9ce8df704c03d1e46a9d12d616a8",
 "version": "0.9.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
