
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-23T18:27:22-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "53c24961d001a40e1e6328514a9289227c9dbb36",
 "version": "v1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
