[tool.poetry]
name = "tsflex"
version = "0.1.0"
description = "Toolkit for flexible operations on time-series data"
authors = ["Emiel Deprost", "Jeroen Van Der Donckt", "Jonas Van Der Donckt"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/tsflex/tsflex"
repository = "https://github.com/tsflex/tsflex"
documentation = "https://github.com/tsflex/tsflex"
keywords = ["time-series", "processing", "feature-extraction", "data-science"]

[tool.poetry.dependencies]
python = "^3.7.1"
pandas = "^1.2.3"
numpy = "^1.19.0"
pathos = "^0.2.7"
tqdm = "^4.60.0"
dill = "^0.3.3"
scikit-learn = "^0.24.2"
fastparquet = "^0.6.3"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.9.0"
pydocstyle = "^5.1.1"
Sphinx = "^3.5.2"
jupyterlab = "^3.0.12"
memory-profiler = "^0.58.0"
pytest = "^6.2.3"
pytest-cov = "^2.12.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
