
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "d74b6594f0ad3fa30ce43f88cd38845ef18b6008",
 "version": "4.0.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
