[tool.poetry]
name = "aws_in_docker"
version = "0.0.1"
description = "Mock EC2 with this moto fork + launch instances in Docker"
authors = ["Leo Gallucci <elgalu3@gmail.com>"]
readme = "README.md"
# https://pypi.org/classifiers/
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Development Status :: 4 - Beta",
]
packages = [{ include = "src", from = "." }]

[tool.poetry.dependencies]
python = "^3.9"
# https://github.com/madzak/python-json-logger
python_json_logger = "^0.1"
PyYAML = "^5.1"

[tool.pylint.'MESSAGES CONTROL']
disable = "bad-continuation,missing-docstring"

[tool.pylint.'REPORTS']
msg-template = "{path}:{line}: [{msg_id}({symbol}),{obj}]{msg}"
reports = "no" # https://docs.sonarqube.org/latest/analysis/languages/python/#pylint

[tool.pytest.ini_options]
junit_family = "legacy"
minversion = "6.0"
addopts = "-ra -q"
testpaths = ["tests"]

[tool.poetry.dev-dependencies]
# pylint = { git = "https://github.com/PyCQA/pylint.git", rev = "8649b721560ac33756792e405a6d7bbf7d331e57" }
pylint = "^2.6"
pytest = "^6.2"
pytest-cov = "^2.8"
pytest-html = "^2.0"
requests_mock = "^1.7"
mypy = { git = "https://github.com/python/mypy.git", rev = "1573336d12ec56454b6a3ed6633acff8bb2c4737" }
# mypy = "^0.902"
autopep8 = "^1.5.4"
invoke = "^1.5.0"
pre-commit = "^2.9.3"
flake8 = "^3.8.4"
black = { version = "^20.8b1", allow-prereleases = true }

[tool.mypy]
# https://dokk.org/documentation/mypy/v0.471/config_file/#global-flags
# exclude = "tasks.py"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = false
warn_redundant_casts = true
warn_unused_ignores = true
disallow_any_generics = true
check_untyped_defs = true
no_implicit_reexport = true
disallow_untyped_defs = true

[tool.black]
# https://black.readthedocs.io/en/stable/pyproject_toml.html#configuration-format
line-length = 101
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"
