name: publish_docs

on:
  release:
    types: [created]

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: install deps and run automatic documentation
        run: |
          python -m pip install --upgrade pip
          python -m pip install pdoc

      - name: run automatic documentation
        run: |
          python -m pdoc pipewire_python/ --docformat google --output-directory docs/html/ --edit-url pipewire_python=https://github.com/pablodz/pipewire_python/tree/main/pipewire_python/

      - name: commit the daily updates
        run: |
          git pull          
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit --allow-empty -m "pdoc updated to latest release" -a

      - name: push my changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
