
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-17T21:54:31+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "eea6f29d4e9581f5e106272e34f1d5e02e582206",
 "version": "4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
