[tool]
[tool.poetry]
name = "techlib-nr-theses-metadata"
version = "1.0.0a13"
description = "Czech National Repository theses data model."
license = "MIT"
keywords = ["Czech", "Nation", "Repository", "Invenio", "theses"]
classifiers = ["Environment :: Web Environment", "Intended Audience :: Developers", "License :: OSI Approved :: MIT License", "Operating System :: OS Independent", "Programming Language :: Python", "Topic :: Internet :: WWW/HTTP :: Dynamic Content", "Topic :: Software Development :: Libraries :: Python Modules", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.7", "Development Status :: 3 - Alpha"]
authors = ["Daniel Kopecký <Daniel.Kopecky@techlib.cz>", "Denys Chaplyhin <chaplyhd@vscht.cz"]
readme = "README.md"
packages = [{include='nr_theses_metadata'}]

[tool.poetry.dependencies]
python = "^3.8"
techlib-nr-common-metadata = "^3.0.0a48"
oarepo = "^3.3.59"

[tool.poetry.dev-dependencies]
oarepo = "^3.3"
oarepo-mapping-includes = "<=1.2.0"
oarepo-invenio-model = "^2.0.1"
oarepo-multilingual = "^2.2.0"
oarepo-taxonomies = "^3.0.0a4"
oarepo-references = "^1.9.0"
oarepo-validate = "^1.2.8"
pytest = "^5.0.0"
pytest-cov = "^2.10.1"
pytest-runner = "^5.2"
oarepo-fsm = "^1.5.0"

[tool.poetry.plugins]

[tool.poetry.plugins.'invenio_jsonschemas.schemas']
'nr_theses_metadata' = 'nr_theses_metadata.jsonschemas'

[tool.poetry.plugins.'oarepo_mapping_includes']
'nr_theses_metadata' = 'nr_theses_metadata.mapping_includes'
