[package]
name = "pywinpty"
version = "1.1.3"
authors = ["Edgar Andrés Margffoy Tuay <andfoy@gmail.com>"]
description = "Pseudo terminal support for Windows from Python."
repository = "https://github.com/spyder-ide/pywinpty"
license = "MIT"
keywords = ["pty", "pseudo-terminal", "conpty", "windows", "winpty"]
readme = "README.md"
edition = "2018"
links = "winpty"

[lib]
name = "winpty"
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.81"
cxx = "1.0.45"

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]

[build-dependencies]
cxx-build = {version = "1.0.45", features = ["parallel"]}
pywinpty_findlib = { version = "=0.3.0", path = "local_dependencies/pywinpty_findlib"}
which = "4.1.0"

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"
targets = ["x86_64-pc-windows-msvc"]

[package.metadata.maturin]
requires-python = ">=3.6"
