language: python
services:
  - docker
env:
  global:
    - KILI_API_ENDPOINT=https://staging.cloud.kili-technology.com/api/label/v2/graphql
    # USER_ID
    - secure: "avQNya43cpJ0vG2LOw0hrgYLqw+SbCsJMqyBTObruQJGOST1Y6FefHRcugsuH4SrZADym5BhxZ5eJ7rKUGa4ukzYsvK9FhciUgS2cVUePwwNzM1tFqUJ5VKX6Ltv1ePcGImCgf3REo+UwdYB6PX9l7foRITs0MtqN9EGi5Gp9u7Sb+z4RGwX4FjZJKdPktuhO6PXmObGq8+3bEOMWUIguEkHuU/4gDYC0A4YQ1Zg//ho3SKnI4StGb9fwFk46KB7Dbr1RgzVjWQP7QlEl+sFAyXK7tHwYqYrxOgv8iSDGxEpRnCJAvtjRoIMD9Z7HNwbkNFkja4dW8mXFZmYVksNB5i6LRuJ4Z7oWBB37U8Cmz5g8VEe2QFszPbh7Dev00yz4GyAubegdaQGj8mZRVCkap8feKXgMnnO4gPjjs6+efHIBQCWoA79nI8EXXJJ/wNHhy38XowA+kP+yYyXWPI2kDDlLTm0MlGiZxV1zoz3p9Vi/eQ7pQKEDZWwiYt3wewuZPoC+ESYasPCLui1EYamjQMfoEQ740Qu4hepKcb9Pq2lSG7ExsFMrJ7kV+kxr6XRMsTuYL7ixfEwGt+BfOCINvTKy2v/q86JXx9aQXg2V/tY2pHCpXHWhvcI3H/o5+e5It9TaqLlw4ZpFXnESjTHbZntVqJwDMum+IHhDCjDB3w="
    # API_KEY
    - secure: "b1ePbDtDqjzCBnVnCionchl2A9fE3cJUXGNgbx85ATmW9Xxk9eIaxXiTE8kWyKNzLcDIuWMIDzVx0XDEgJWysxrlfQa8rLD9+TcqTR78ARlUb/+pJxC4pu7JKVqdSb+NXmGXrpmBedjyfxdz3VTWHpulHDp444HQVlpJ2lApW6ONGgkm4s3mC2WtQcJJQuiCpRzUUT/ttTR7QuHLHRQI4k4fndBNzvL9uMYKhf1dG1ver7XAunBKI7YTyLveobGyi5ly9ds5WKylzzAAzrln8gRqGgLbYJMSEMQtJ+QP1ToflXDjO5HcxBUJzF3lZtI+f8A5wfoRScxPT3tKcoyWfTg49sSQmoGFdcrfD04CEJ1o3RpPnjjZoP34uIGDRL41Sr/gHGmgCleB+Klfnl4wkywTUV4veJUwlEj+s/hURUKnNspTpXKZgwGiiYWfi7UlWAdc/FpUPxz0zZpxxxSJSVvzZjMChYBYxmWSv9y+G/OhYhbORVXCYf0uggdZ6aapiSxicgrY8Pb/KUZyLMMiAdREKWvmp/aezaH3shdcd6KqK9zQCE7AnwRGJLSTQMU6537et9IGupHc+GsPuPV4CeDJZsqIcMpUpLLDZGlxHno8CMPVCnDTaUOt43LR7auwMPEVKFvhj7UmK2S0kujXnx9GSZ7OjyNl9VSENC56EfM="
    # USER_EMAIL
    - secure: "wF5TlQNogtACtGA7mTCRWBmAr/F8eK7UtOAjlcJD19SFuevuAMjj9IsKPQzavbeQJNRouvK/B8G88DBENjIIlWmhLqEtgWcDAF90oLmtw2SdhSXKBWXrSvMF7IV4SU6cQJ/kxZABaMOzGTGrTFvnYlfwgBaeoCS/t8fG1SBn/KvvQ+TiV21Fy8jD7R1sDAL218gwQgX5WpmIuL52/4bTmz1ZBe0M5OwCSpXlCghTzXzVq4NNq6KZGGw91NaC0PYv4GfROQBGapMK4g8noShcC0TytLo1Gt6EyntYP8mYpWwTUVbhwdIT1SM4JHh/FS0bhP3SmnUKONHvhMC8c197Cq3dqB9SPDxOXGOwNYA14d/u7CiW2S/KMbmXleQEmatgQ2O9CCiRqLCcYTbsstBjMlSlDJ0DUoIBPrVPiZTjTqaEf6NoNiih1v0RC9hsA6HTCMGIiAk2+Cvkzl5zI5DQBZcbAbhceAUXxybjtCq+Y4pRcStV3QQalnNHClAOpCvihBApJ9NzqK+CIG0QU59MIxgfH602FrfcNZjey7p0ci790a68J/Bo9UfTaJOlxOOtOobwziOyz8KMA8dUvsCSQp+fbHrMedTBXxuzK4XaCE6V0PINDwlR4ByLsnyJJKt/9uhSOLqlmmLVVDMn1vQfulTn/Mswc3147QgdTnxlANU="
    # DOCKER_USERNAME
    - secure: "rx+VNeb2V3/bbZYIdDBJnrIg13JGjSqKm9jLB5RNzhs2R64wIIDBbJk7Bt9VEs4i8mQyrhOt/KTfNkNaZAHwH7b0o1c433tt0yIJI9V7vihn/ZuHgCvnB33GrDtWvXXpi0uAsYSlthVcBje9CvthOHHK6I1tuQZR6gTAR3e1ZniziOYB0AeaHQreWENZqkG8kuL8NXPZjgy0kubIzzUS5imPozlaNZxW2r33j4R2Z5XWp0x4inoWJEW0Ge2ieT6iV0JozpvH6iMsVzdKHtI6ku28+gr5gb57ZEpt9m9bB78Av0aD38f+4eHoRHaqEFvJKlQNaF1FhgHt6CkT7sPWfPUgjSHbgdzXkyLnqHNj6sXjv0D5uiJtbH2fFxLt9aM8zpwciifEEwSl8fBsSOdE3CeP+hQDTakp0Ot1w5c3rsOy5aPOVv19Vg5tjapDlZ5ysM2aCZEQgZ+ygB9roDyzdXCJhPvd1zAGDm8y5tYVmbPo3WwARowzHptm/mFUs39y4HeYEwSMCzW99ihN7Z/3zZglU0qeO1zl00WwCTD+EisDbjfNvNQfxb6gAVQFym8WaspD10L5QjnRs1tVFNzoxlAwdEoIyDa85OHWemGrQA1na+Cm5zdy8uFZ6ki45WcM3vmPFwe2DQ/zh7+VtBi6m4nokzl9nFxbqoSjqI87Rf8="
    # DOCKER_PASSWORD
    - secure: "fzJ+dTZYMc8b+K/YK13ZLYojZPWwOlv2qnxCfwz7lpAEWsRF2wRqAYfm/ilDZHdTnTBvi9d9WGGn9iBbyCqNxvijlkS3p7f+yWPl3TTjsVies3QBIUHqNVC2ySYnDZQqQ793whgYeqddCcGF8frtjhQj28OLN/AD5btXoYMjVLlRNvtQvXzik/EGVl3yhplYQHH9kcXSqFiQTcyu1ZoGNQdtDVgBLyg8sTOKX3vV37C1UgUwZHiQ36vA07/BqkafKJxK7unGaKQnvlSSxv3dR9ywh34jTyny/j1Jl8Pz5YUKGhF2ExXduFcZULE9+IkGY8uIwSOC1Tm/OM544bvqEeyKXneKzi7CJZiOlK5BNbFaJs2dsucz2UdifAN4ecew1n/dV+MArmlFHV1Ux9YIsNX9yjQboyaisZRGpt4390BpVLYjts3WuSvabvCgFH5bDsfM+ejMoRlZ4lE1CgIyVTECYeMAU3kBcp7sDXgtkcfsCe5sv2MvVdAEJtvEE0ZGaGDPZZKzJutDWgV/EBfraRhtvp11ktDIx+C9ogfKxBN4x5G8MqdHCiL+f0KJk/2hU0sEIC7ssexm/ArZCzDzod6RQTUVFFRXMdGtoYtyRQNay+/wt5oCECe7nvfvyl8gKNdslYGuqDfRzorqtYdslyeFD3z3urOyQYsFN6tqUNI="
jobs:
  include:
    # To debug a recipe by running it in a Docker locally as it is run in Travis, launch the following lines:
    #
    # DOCKER_IMAGE=continuumio/anaconda3:2020.02
    # KILI_USER_API_KEY=...
    # KILI_USER_ID=...
    # TRAVIS_BRANCH=...
    #
    # docker pull ${DOCKER_IMAGE}
    #
    # docker run \
    #   --env KILI_API_ENDPOINT=https://staging.cloud.kili-technology.com/api/label/v2/graphql \
    #   --env KILI_USER_API_KEY=${KILI_USER_API_KEY} \
    #   --env KILI_USER_ID=${KILI_USER_ID} \
    #   --env KILI_USER_EMAIL=${KILI_USER_EMAIL} \
    #   --rm \
    #   -p 10000:8888 \
    #   ${DOCKER_IMAGE} /bin/sh -c "cd /root && \
    #     apt-get update && apt-get install -y gcc && \
    #     git clone --branch ${TRAVIS_BRANCH} https://github.com/kili-technology/kili-playground.git && \
    #     pip install ./kili-playground && \
    #     jupyter notebook --allow-root --ip=0.0.0.0 --port=8888"
    #
    # Then start http://localhost:10000/?token=TOKEN_OUTPUTED_IN_CONSOLE
    - &test-recipes
      stage: Test *.ipynb in recipes
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker pull ${DOCKER_IMAGE}
        - |
          docker run \
            --env KILI_API_ENDPOINT=${KILI_API_ENDPOINT} \
            --env KILI_USER_ID=${KILI_USER_ID} \
            --env KILI_USER_API_KEY=${KILI_USER_API_KEY} \
            --env KILI_USER_EMAIL=${KILI_USER_EMAIL} \
            ${DOCKER_IMAGE} /bin/sh -c "cd /root && \
              apt-get update && apt-get install -y gcc && \
              git clone --branch ${TRAVIS_BRANCH} https://github.com/kili-technology/kili-playground.git && \
              pip install ./kili-playground && \
              jupyter nbconvert \
                --to notebook \
                --ExecutePreprocessor.kernel_name=python3 \
                --ExecutePreprocessor.timeout=1000 \
                --execute /root/kili-playground/${NOTEBOOK_PATH}"
      env:
        - DOCKER_IMAGE=continuumio/anaconda3:2020.02
        - NOTEBOOK_PATH=recipes/transfer_learning_with_yolo.ipynb
    - <<: *test-recipes
      env:
        - DOCKER_IMAGE=continuumio/anaconda3:2020.02
        - NOTEBOOK_PATH=recipes/import_predictions.ipynb
    - <<: *test-recipes
      env:
        - DOCKER_IMAGE=continuumio/anaconda3:2020.02
        - NOTEBOOK_PATH=recipes/create_project.ipynb
    - <<: *test-recipes
      env:
        - DOCKER_IMAGE=continuumio/anaconda3:2020.02
        - NOTEBOOK_PATH=recipes/medical_imaging.ipynb
    - <<: *test-recipes
      env:
        - DOCKER_IMAGE=continuumio/anaconda3:2020.02
        - NOTEBOOK_PATH=recipes/query_methods.ipynb
    - <<: *test-recipes
      env:
        - DOCKER_IMAGE=continuumio/anaconda3:2020.02
        - NOTEBOOK_PATH=recipes/import_assets.ipynb
    - <<: *test-recipes
      env:
        - DOCKER_IMAGE=continuumio/anaconda3:2020.02
        - NOTEBOOK_PATH=recipes/pixel_level_masks.ipynb
    - <<: *test-recipes
      env:
        - DOCKER_IMAGE=continuumio/anaconda3:2020.02
        - NOTEBOOK_PATH=recipes/import_text_assets.ipynb
    - <<: *test-recipes
      env:
        - DOCKER_IMAGE=continuumio/anaconda3:2020.02
        - NOTEBOOK_PATH=recipes/export_labels.ipynb
    - <<: *test-recipes
      env:
        - DOCKER_IMAGE=continuumio/anaconda3:2020.02
        - NOTEBOOK_PATH=recipes/getting-started/getting_started-image_bounding_box_detection.ipynb
    - <<: *test-recipes
      env:
        - DOCKER_IMAGE=continuumio/anaconda3:2020.02
        - NOTEBOOK_PATH=recipes/getting-started/getting_started-image_classification.ipynb
