
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-17T18:11:52-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "fbb39d66f2290acc9af37471b3728a96794d372b",
 "version": "0.16.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
