
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-23T18:12:58+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "43419da43b0643cab7a99b5b1350b5992831daad",
 "version": "1.6.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
