set_zone_moisture_percent:
  name: Set Zone Moisture Percent
  description: Set the moisture percentage of a zone or list of zones.
  target:
    entity:
      integration: rachio
      domain: switch
  fields:
    percent:
      name: Percent
      description: Set the desired zone moisture percentage from 0 to 100.
      required: true
      example: 50
      selector:
        number:
          min: 0
          max: 100
          mode: slider
          unit_of_measurement: "%"
          step: 1
start_multiple_zone_schedule:
  name: Start Multiple Zones
  description: Create a custom schedule of zones and runtimes. Note that all zones should be on the same controller to avoid issues.
  target:
    entity:
      integration: rachio
      domain: switch
  fields:
    duration:
      name: Duration
      description: Number of minutes to run the zone(s). If only 1 duration is given, that time will be used for all zones. If given a list of durations, the durations will apply to the respective zones listed above.
      example: 15, 20
      required: true
      selector:
        object:
pause_watering:
  name: Pause Watering
  description: Pause any currently running zones or schedules.
  fields:
    devices:
      name: Devices
      description: Name of controllers to pause. Defaults to all controllers on the account if not provided.
      example: "Main House"
      selector:
        text:
    duration:
      name: Duration
      description: The number of minutes to pause running schedules. Accepts 1-60. Default is 60 minutes if not provided.
      example: 60
      default: 60
      selector:
        number:
          min: 1
          max: 60
          mode: slider
          unit_of_measurement: "minutes"
          step: 1
resume_watering:
  name: Resume Watering
  description: Resume any paused zone runs or schedules.
  fields:
    devices:
      name: Devices
      description: Name of controllers to resume. Defaults to all controllers on the account if not provided.
      example: "Main House"
      selector:
        text:
