repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.19.4
    hooks:
      - id: pyupgrade
  - repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
      - id: black
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.10.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [ black==21.6b0 ]
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: rst-backticks
  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.17.0
    hooks:
      - id: setup-cfg-fmt
        args: [--min-py3-version, "3.6", "--max-py-version", "3.10"]
  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: "0.5.0"
    hooks:
      - id: tox-ini-fmt
        args: ["-p", "fix"]
  - repo: https://github.com/PyCQA/flake8
    rev: "3.9.2"
    hooks:
      - id: flake8
        additional_dependencies: [
            "flake8-bugbear == 21.4.3",
            "flake8-unused-arguments == 0.0.6",
            "flake8-comprehensions == 3.5.0",
            "flake8-spellcheck == 0.24.0",
            "flake8-pytest-style == 1.4.2",
        ]
