[tool.poetry]
name = "asc2mb"
version = "0.2.0"
description = "Parse XML export from asc and format into two files suitable for upload"
authors = ["Adam Morris <adam.morris@fariaedu.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
click = "8.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
asc2mb = 'asc2mb.asc2mb:main'
