
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-25T10:00:19+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "878f791bb6d5e8ae22b3d3739edb4835a03b856a",
 "version": "2.6.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
