[build-system]
requires = ["setuptools >= 40.6.0", "wheel"]
build-backend = "setuptools.build_meta"


[tool.black]
line-length = 120
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120

[tool.tox]
legacy_tox_ini = """
[tox]
envlist=
    lint
    py{38}

[testenv]
skip_install = true
usedevelop = true
deps =
    -rrequirements.txt
    -rrequirements-test.txt
commands =
    {posargs:python -m pytest tests/}
whitelist_externals = bash

[testenv:lint]
deps = pre-commit
changedir = {toxinidir}
commands =
    pre-commit run --all-files

whitelist_externals = bash

[gh-actions]
python =
    3.8: py38, lint
"""
