[tool.poetry]
name = "thechef_filler"
version = "0.1.3"
description = ""
authors = ["kohkubo <kohkubo@student.42tokyo.jp>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.scripts]
thechef_filler = "thechef_filler:main"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
