[tool.poetry]
name = "puchipuchi_filler"
version = "0.1.7"
description = "no description provided"
authors = ["puchipuchi team"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
puchipuchi_filler = "puchipuchi_filler.main:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
