# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from th2_grpc_crawler_check2 import crawler_check2_pb2 as th2__grpc__crawler__check2_dot_crawler__check2__pb2
from th2_grpc_data_provider import data_provider_template_pb2 as th2__grpc__data__provider_dot_data__provider__template__pb2


class Check2Stub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.crawlerConnect = channel.unary_unary(
                '/th2.crawler.Check2/crawlerConnect',
                request_serializer=th2__grpc__crawler__check2_dot_crawler__check2__pb2.CrawlerInfo.SerializeToString,
                response_deserializer=th2__grpc__crawler__check2_dot_crawler__check2__pb2.Check2Info.FromString,
                )
        self.sendEvent = channel.unary_unary(
                '/th2.crawler.Check2/sendEvent',
                request_serializer=th2__grpc__data__provider_dot_data__provider__template__pb2.EventData.SerializeToString,
                response_deserializer=th2__grpc__crawler__check2_dot_crawler__check2__pb2.EventResponse.FromString,
                )
        self.sendMessage = channel.unary_unary(
                '/th2.crawler.Check2/sendMessage',
                request_serializer=th2__grpc__data__provider_dot_data__provider__template__pb2.MessageData.SerializeToString,
                response_deserializer=th2__grpc__crawler__check2_dot_crawler__check2__pb2.MessageResponse.FromString,
                )


class Check2Servicer(object):
    """Missing associated documentation comment in .proto file."""

    def crawlerConnect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sendEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Check2Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'crawlerConnect': grpc.unary_unary_rpc_method_handler(
                    servicer.crawlerConnect,
                    request_deserializer=th2__grpc__crawler__check2_dot_crawler__check2__pb2.CrawlerInfo.FromString,
                    response_serializer=th2__grpc__crawler__check2_dot_crawler__check2__pb2.Check2Info.SerializeToString,
            ),
            'sendEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.sendEvent,
                    request_deserializer=th2__grpc__data__provider_dot_data__provider__template__pb2.EventData.FromString,
                    response_serializer=th2__grpc__crawler__check2_dot_crawler__check2__pb2.EventResponse.SerializeToString,
            ),
            'sendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.sendMessage,
                    request_deserializer=th2__grpc__data__provider_dot_data__provider__template__pb2.MessageData.FromString,
                    response_serializer=th2__grpc__crawler__check2_dot_crawler__check2__pb2.MessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'th2.crawler.Check2', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Check2(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def crawlerConnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/th2.crawler.Check2/crawlerConnect',
            th2__grpc__crawler__check2_dot_crawler__check2__pb2.CrawlerInfo.SerializeToString,
            th2__grpc__crawler__check2_dot_crawler__check2__pb2.Check2Info.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def sendEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/th2.crawler.Check2/sendEvent',
            th2__grpc__data__provider_dot_data__provider__template__pb2.EventData.SerializeToString,
            th2__grpc__crawler__check2_dot_crawler__check2__pb2.EventResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def sendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/th2.crawler.Check2/sendMessage',
            th2__grpc__data__provider_dot_data__provider__template__pb2.MessageData.SerializeToString,
            th2__grpc__crawler__check2_dot_crawler__check2__pb2.MessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
