# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: th2_grpc_crawler_check2/crawler_check2.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from th2_grpc_common import common_pb2 as th2__grpc__common_dot_common__pb2
from th2_grpc_data_provider import data_provider_template_pb2 as th2__grpc__data__provider_dot_data__provider__template__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='th2_grpc_crawler_check2/crawler_check2.proto',
  package='th2.crawler',
  syntax='proto3',
  serialized_options=b'\n$com.exactpro.th2.crawler.check2.grpcP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n,th2_grpc_crawler_check2/crawler_check2.proto\x12\x0bth2.crawler\x1a\x1cth2_grpc_common/common.proto\x1a\x33th2_grpc_data_provider/data_provider_template.proto\",\n\x0b\x43rawlerInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\"q\n\nCheck2Info\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x1c\n\x08\x65vent_id\x18\x03 \x01(\x0b\x32\x08.EventIDH\x00\x12 \n\nmessage_id\x18\x04 \x01(\x0b\x32\n.MessageIDH\x00\x42\x04\n\x02id\"%\n\rEventResponse\x12\x14\n\x02id\x18\x01 \x01(\x0b\x32\x08.EventID\")\n\x0fMessageResponse\x12\x16\n\x02id\x18\x01 \x01(\x0b\x32\n.MessageID2\xc3\x01\n\x06\x43heck2\x12\x45\n\x0e\x63rawlerConnect\x12\x18.th2.crawler.CrawlerInfo\x1a\x17.th2.crawler.Check2Info\"\x00\x12\x35\n\tsendEvent\x12\n.EventData\x1a\x1a.th2.crawler.EventResponse\"\x00\x12;\n\x0bsendMessage\x12\x0c.MessageData\x1a\x1c.th2.crawler.MessageResponse\"\x00\x42(\n$com.exactpro.th2.crawler.check2.grpcP\x01\x62\x06proto3'
  ,
  dependencies=[th2__grpc__common_dot_common__pb2.DESCRIPTOR,th2__grpc__data__provider_dot_data__provider__template__pb2.DESCRIPTOR,])




_CRAWLERINFO = _descriptor.Descriptor(
  name='CrawlerInfo',
  full_name='th2.crawler.CrawlerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='th2.crawler.CrawlerInfo.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='th2.crawler.CrawlerInfo.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=188,
)


_CHECK2INFO = _descriptor.Descriptor(
  name='Check2Info',
  full_name='th2.crawler.Check2Info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='th2.crawler.Check2Info.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='th2.crawler.Check2Info.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='event_id', full_name='th2.crawler.Check2Info.event_id', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message_id', full_name='th2.crawler.Check2Info.message_id', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='id', full_name='th2.crawler.Check2Info.id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=190,
  serialized_end=303,
)


_EVENTRESPONSE = _descriptor.Descriptor(
  name='EventResponse',
  full_name='th2.crawler.EventResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='th2.crawler.EventResponse.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=342,
)


_MESSAGERESPONSE = _descriptor.Descriptor(
  name='MessageResponse',
  full_name='th2.crawler.MessageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='th2.crawler.MessageResponse.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=344,
  serialized_end=385,
)

_CHECK2INFO.fields_by_name['event_id'].message_type = th2__grpc__common_dot_common__pb2._EVENTID
_CHECK2INFO.fields_by_name['message_id'].message_type = th2__grpc__common_dot_common__pb2._MESSAGEID
_CHECK2INFO.oneofs_by_name['id'].fields.append(
  _CHECK2INFO.fields_by_name['event_id'])
_CHECK2INFO.fields_by_name['event_id'].containing_oneof = _CHECK2INFO.oneofs_by_name['id']
_CHECK2INFO.oneofs_by_name['id'].fields.append(
  _CHECK2INFO.fields_by_name['message_id'])
_CHECK2INFO.fields_by_name['message_id'].containing_oneof = _CHECK2INFO.oneofs_by_name['id']
_EVENTRESPONSE.fields_by_name['id'].message_type = th2__grpc__common_dot_common__pb2._EVENTID
_MESSAGERESPONSE.fields_by_name['id'].message_type = th2__grpc__common_dot_common__pb2._MESSAGEID
DESCRIPTOR.message_types_by_name['CrawlerInfo'] = _CRAWLERINFO
DESCRIPTOR.message_types_by_name['Check2Info'] = _CHECK2INFO
DESCRIPTOR.message_types_by_name['EventResponse'] = _EVENTRESPONSE
DESCRIPTOR.message_types_by_name['MessageResponse'] = _MESSAGERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CrawlerInfo = _reflection.GeneratedProtocolMessageType('CrawlerInfo', (_message.Message,), {
  'DESCRIPTOR' : _CRAWLERINFO,
  '__module__' : 'th2_grpc_crawler_check2.crawler_check2_pb2'
  # @@protoc_insertion_point(class_scope:th2.crawler.CrawlerInfo)
  })
_sym_db.RegisterMessage(CrawlerInfo)

Check2Info = _reflection.GeneratedProtocolMessageType('Check2Info', (_message.Message,), {
  'DESCRIPTOR' : _CHECK2INFO,
  '__module__' : 'th2_grpc_crawler_check2.crawler_check2_pb2'
  # @@protoc_insertion_point(class_scope:th2.crawler.Check2Info)
  })
_sym_db.RegisterMessage(Check2Info)

EventResponse = _reflection.GeneratedProtocolMessageType('EventResponse', (_message.Message,), {
  'DESCRIPTOR' : _EVENTRESPONSE,
  '__module__' : 'th2_grpc_crawler_check2.crawler_check2_pb2'
  # @@protoc_insertion_point(class_scope:th2.crawler.EventResponse)
  })
_sym_db.RegisterMessage(EventResponse)

MessageResponse = _reflection.GeneratedProtocolMessageType('MessageResponse', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGERESPONSE,
  '__module__' : 'th2_grpc_crawler_check2.crawler_check2_pb2'
  # @@protoc_insertion_point(class_scope:th2.crawler.MessageResponse)
  })
_sym_db.RegisterMessage(MessageResponse)


DESCRIPTOR._options = None

_CHECK2 = _descriptor.ServiceDescriptor(
  name='Check2',
  full_name='th2.crawler.Check2',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=388,
  serialized_end=583,
  methods=[
  _descriptor.MethodDescriptor(
    name='crawlerConnect',
    full_name='th2.crawler.Check2.crawlerConnect',
    index=0,
    containing_service=None,
    input_type=_CRAWLERINFO,
    output_type=_CHECK2INFO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='sendEvent',
    full_name='th2.crawler.Check2.sendEvent',
    index=1,
    containing_service=None,
    input_type=th2__grpc__data__provider_dot_data__provider__template__pb2._EVENTDATA,
    output_type=_EVENTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='sendMessage',
    full_name='th2.crawler.Check2.sendMessage',
    index=2,
    containing_service=None,
    input_type=th2__grpc__data__provider_dot_data__provider__template__pb2._MESSAGEDATA,
    output_type=_MESSAGERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHECK2)

DESCRIPTOR.services_by_name['Check2'] = _CHECK2

# @@protoc_insertion_point(module_scope)
