[tool.poetry]
name = "super_ryaoi_filler"
version = "0.3.0"
description = ""
authors = ["ntoshihi <ntoshihi@student.42tokyo.jp>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
super_ryaoi_filler = "super_ryaoi_filler.nori.py:main"