
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-17T17:21:34-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "bcb69aa2f77e6dcc2e13477447538b6dcdc5b973",
 "version": "4.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
