[tool.poetry]
name = "pynfogen"
version = "0.4.1"
description = "Scriptable MediaInfo-fed NFO Generator for Movies and TV"
license = "MIT"
authors = ["PHOENiX <rlaphoenix@pm.me>"]
maintainers = ["PHOENiX <rlaphoenix@pm.me>"]
readme = "README.md"
homepage = "https://github.com/rlaphoenix/pynfogen"
repository = "https://github.com/rlaphoenix/pynfogen"
documentation = "https://github.com/rlaphoenix/pynfogen"
keywords = ["python", "nfo", "generator", "scriptable"]
classifiers = [
    # python ver and license set by poetry automatically
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: End Users/Desktop",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Topic :: Documentation",
    "Topic :: Multimedia",
    "Topic :: Multimedia :: Video",
    "Topic :: Multimedia :: Video :: Conversion"
]
include = ["LICENSE", "README.md"]

[tool.poetry.dependencies]
python = ">=3.6,<4.0"
poetry-dynamic-versioning = "^0.13.0"
PyYAML = "^5.4.1"
pymediainfo = "^5.1.0"
pvsfunc = "^4.0.3"
pyd2v = "^1.2.0"
pycountry = "^20.7.3"
requests = "^2.25.1"
appdirs = "^1.4.4"
click = "^8.0.0"
dunamai = "^1.5.5"

[tool.poetry-dynamic-versioning]
enable = false
style = "semver"
latest-tag = true

[tool.poetry.scripts]
nfo = "pynfogen.cli:cli"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
