[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = 'pyJsonEdit'
version = '1.0.4'
description = 'Edit parts of json strings & files while keeping the orginal, inconsistent formating'
license = "MIT"
authors = ["Dawid Urbanski <kontakt@dawidurbanski.pl>"]
repository = "https://github.com/UrbanskiDawid/pyJsonEditor"
readme = "README.md"
include = ["pyjsonedit/*.py"]

[tool.poetry.dependencies]
python = '^3.6'

pylint = '2.8.2'
pytest = '6.2.4'
coverage = '5.5'

[tool.poetry.scripts]
pyjsonedit-mask = "pyjsonedit.cli:run_mask"
pyjsonedit-modify = "pyjsonedit.cli:run_modify"