#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['cross_section']

package_data = \
{'': ['*']}

setup(name='cross_section',
      version='0.0.1.dev0',
      description='Structural cross-section analysis.',
      author='Patrick Simon',
      author_email='mail@patricksimon.info',
      url=None,
      packages=packages,
      package_data=package_data,
     )
