[tool.black]
target-version = ['py38']
line-length = 79
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''

[tool.poetry]
name = "stimpy"
version = "0.0.1"
description = "A PsychoPy wrapper to create moving visual stimuli without loops."
authors = ["Ka Chung Lam <kclamar@connect.ust.hk>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.21.0"
PsychoPy = "^2021.2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
